### ISSUE TITLE
Idea: auto add group_gatekeeper check to entity_gate_keeper

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10030]
if using `elgg_entity_gatekeeper`, you also need to check the group_gatekeeper (if using in resource views). Would it be nice to have the entity_gatekeeper also check the group_gatekeeper for the container of the entity??

**Comment by mrclay** [comment]
Probably a good idea. If anyone is using elgg_entity_gatekeeper but not group_gatekeeper, it's probably by mistake. The only reason to do that is to let a page "peek" out of the visibility settings and I bet that's pretty rare.

Still there's a (tiny) chance that a plugin is relying on this behavior. 👍 for adding in 3.0. Not sure about 2.x.

**Comment by mrclay** [comment]
Hmm, one issue in combining them. Consider this code (e.g. in our own discussion view):
```php
elgg_entity_gatekeeper($guid, 'object', 'discussion');
$topic = get_entity($guid);
elgg_set_page_owner_guid($topic->container_guid);
elgg_group_gatekeeper();
```
Here the group gatekeeper works because it runs after the page owner is set. If we tell people the entity gatekeeper handles it, and they remove the group gatekeeper call, this will no longer provide protection.

I think in general we should move towards more explicit usage. Maybe group gatekeeper should issue a warning if there's no page_owner set...

**Comment by hypeJunction** [comment]
Die page owner, die. We need to move all core plugins to using page_owner hook instead of explicit declarations in views.
One way to protect group views is to hook into view vars and refuse to serve layout content.

**Comment by jdalsem** [comment]
what if we add a toggle param to the entity_gate_keeper... if set to true it will check the container_guid (if it is a group) with the group_gatekeeper function

**Comment by jdalsem** [comment]
Has been added as part of https://github.com/Elgg/Elgg/pull/11578
