### ISSUE TITLE
User table and entity table last action are not in sync

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10097]
Whenever last action is updated in user table, it should be updated in the entity table, IMO

**Comment by mrclay** [comment]
http://learn.elgg.org/en/latest/design/database.html#schema We should redefine time_updated to be the last save(), and formally define last_action as the time of the last engine boot with the user logged in (we don't count authenticated web services requests). I think the current behavior is correct.

I don't like that we have to do a DB write on every boot (e.g. messes with caching) but it simplifies things.

**Comment by hypeJunction** [comment]
User table is updated with a delayed query. Entity table is updated instantly.

**Comment by mrclay** [comment]
I forgot both tables have `last_action` 😢. What mechanism is updating `entities.last_action`? I don't see anything calling `update_entity_last_action` for users.

I don't even see a way to access that value for a user, since `users_entity.last_action` masks it. We should document these in the ElggEntity/ElggUser class phpdocs.

**Comment by hypeJunction** [comment]
I didn't dig into details, just noticed the discrepancy during testing.

**Comment by hypeJunction** [comment]
Fixed in #10099
https://github.com/Elgg/Elgg/pull/10099/files#diff-df6c6c153d1302dc0a675c11aa993c0cR571
