### ISSUE TITLE
the enable/disable all plugins buttons are not functioning

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10165]
Something registered lightboxes on these buttons, but they should be normal actions. At least the action is not executed.

**Comment by mrclay** [comment]
These work fine for me. Do you get JS errors?

**Comment by iionly** [comment]
I tried to debug. No errors logged. But it might be a browser specific issue. The culprits seems to have started with https://github.com/Elgg/Elgg/commit/f675cce0419b8bfcc37da7034ecf45230177f907.

On Firefox it fails to work for me. The action is never called. I don't know if the submit already fails or if the submit is triggered but something goes wrong then. On Chrome it seems to work (can't say for sure at the moment because I've changed the JS code while trying to get it to work on Firefox first).

But even on Chrome it might not work flawless. I had quite a number of plugins disabled that have some dependencies between each other (i.e. plugin a requires plugin b which requires plugin c to be enabled first). When I click on "Activate all" I get a fatal error / error 500. I guess Elgg tries to enable the plugins in the "wrong" order.

**Comment by iionly** [comment]
I have a fix for the issue with the submit not working in Firefox.

But the fatal error on plugin activation is still an (additional) issue. How and when are classes provided by a plugin loaded? Could the reason for the fatal error be due to a plugin activated in the activation loop but it's class(es) not yet loaded?

**Comment by iionly** [comment]
I've opened a separate issue for the problem with plugin dependencies: https://github.com/Elgg/Elgg/issues/10181.

**Comment by mrclay** [comment]
Fixed by #10180
