### ISSUE TITLE
Simplify personal notifications metadata

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#10185]
Current structure:

``` php
$user->{notification:method:email} = true;
$user->{notification:method:sms} = true;
$user->{notification:method:notifier} = true;
```

Potential replacement:

``` php
$user->personal_notification_methods = ['email', 'sms', 'notifier']
```

Or perhaps personal notifications should use relationships, so the data would be in line with how subscription notifications are saved. This would allow more granular subscriptions. User could e.g. get like notifications only via notifier but comment notifications also via email.

**Comment by hypeJunction** [comment]
I want to eventually add a generic way to store and retrieve subscription preferences for any arbitrary notification type, e.g. event  reminders, tag subscrptions etc. I think as long as we don't expose metadata names and have convenience methods to get/set values, this issue is not really a problem.

**Comment by jdalsem** [comment]
Removing from 3.0 milestone. Correct approach is still unclear for this issue
