### ISSUE TITLE
Improve user relations feature

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10330]
We call it "friends" but it isn't reciprocal. It's really a followers model but you have to change all these translations.

I feel like outside the walls of Facebook most sites are using "follower" terminology that implies lighter social connection. Wherever the wind has blown here let's catch up and make it easier either way.

**Comment by mrclay** [comment]
From an API perspective I think that means exposing whether friends is reciprocal and maybe the word to use in URLs.

**Comment by iionly** [comment]
May I suggest a different approach.

I think the problem / diffculty to understand with the Friends vs. Follower terminology might be due to two functionalities being mixed up here:

1. access control (friends access level),
2. notification subscriptions.

And both functionalities seem important to me - the friends access level maybe comes first though.

The only thing lacking a FULL friends model is reciprocal friendship handling. And this is what people might confuse not only due to the usage of the term friend but also in the outcome of making a user a friend ("He's a friend of mine but I still can't see the content he added with friend access level !?").

My suggestion here: pull in the functionality of the Friends Request plugin of Coldtrick into core and this part of the problem would be fixed (what do you think @jdalsem, @jeabakker).

Subscribe to receiving notifications on new content/comments etc of a user is what is meant with "Follower / following" if you ask me. The current problem is that I can subscribt to notifications only of a user is a "Friend" due to friends picker being used in the notification settings. Wouldn't the replacement of the friends picker with an autocomplete input fix this problem in an elegant way automatically - simply don't require the other user being a friend but offer the option to subcribe for receiving notifications from ALL users. Then there's no need to call it "Follower" (or "Friend") anymore in this context - as it's just handling of receiving of notifications (and if you are not "Friend" with the other user you will just not receive notifcations on adding content with friend access level).

So: adding Friend request plugin functionality would clarify and fix the reciprocal friending issue (meaning: Elgg would have a full friends model), and the re-work of the notification settings interface already in the works would allow for adding a full "Follower model" for free with the pseudo-following functionality fully separated from the Friends functionality.
