### ISSUE TITLE
elgg_get_page_owner_entity should return entities

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#10361]
0d33310031024aa8940f9d3bbe5cdd80f2a4da57 broke some long standing functionality that the pageowner could be any entity (not just user or group)

you can set the page_owner to any guid, but elgg_get_page_owner_entity only returns if user or group.

For us this broke at least [Widget manager](https://github.com/ColdTrick/widget_manager) and [Static](https://github.com/ColdTrick/static)

**Comment by beck24** [comment]
ooh yeah, I have some plugins that would break as well

**Comment by mrclay** [comment]
I created this confusion 3 years ago: https://github.com/Elgg/Elgg/commit/85e4c16f39a8b00b229644bcd175663541dfd51a#diff-41a4b46bb948ac08bbdf8d1ecba268dbL42

The security issue was the access bypass so we can just eliminate that type check, make the return type `ElggEntity|false`, and since no bundled plugins have ever strayed outside user/group it would be good to formally mention we support this. Maybe in guides/page-owner.rst

**Comment by jeabakker** [comment]
i take it i should fix this on 1.12?
