### ISSUE TITLE
Allow more /serve-file responses to be proxy cached

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10503]
There are 2 ways to make these functions produce URLs that can't be cached by proxy servers:
1. Bind to session cookie
2. Set a relative expiration date. e.g. "+2 hours"

If a user wants to subvert the privacy of another, re-posting the content is how it will happen, so I assert binding to session cookie is always overkill and shouldn't be something core code does (but we shouldn't change the functions' defaults for BC).

The remaining problem is that relative expirations mean the URL constantly changes. If core uses expirations, we should use a stepping function so that users all get the same URL during the period.

**Comment by mrclay** [comment]
Elgg\FileService\File::setExpires should allow an int to be given as an absolute timestamp. The type in the PHPdoc says "int" but that's wrong.

**Comment by jdalsem** [comment]
After a thought i am closing this because:
- session protected urls are not meant to be cached
- usecases will be very limited for 'download' urls that need to be cacheable
- use `get_inline_url` for cacheable resources
- if you want a cacheable download url, you can control this by passing cookie => false and timeout => custom int (or 0 for infinite)
