### ISSUE TITLE
canComment issues

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10536]
PHP (errno 2048): 2016-10-28 10:47:41 (CEST): "Declaration of ElggBlog::canComment() should be compatible with ElggObject::canComment($user_guid = 0, $default = NULL)"

Declaration of ElggWire::canComment() should be compatible with ElggObject::canComment($user_guid = 0, $default = NULL)

**Comment by hypeJunction** [comment]
Hm, didn't think that the signature would cause issues, but I guess it does. Should we revert as it is a breaking change in a way, it will affect plugins that redeclare canComment. In 3.0, we should probably make all methods that trigger a hook final within ElggObject (`canComment()`, `getURL()` etc) - plugins should use hooks to override those values, otherwise it creates havoc.

**Comment by jdalsem** [comment]
well it is just a notice...

**Comment by jdalsem** [comment]
Fixed in #10654
