### ISSUE TITLE
master: can't upgrade when security settings upgrade + multisite removal is needed

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10559]
reason... multisite checks for multiple sites in config... when doing the security settings upgrade, site_guid 0 is added...

**Comment by juho-jaakkola** [comment]
We need to run `2016102500-3.0.0-remove_site_guid-4a62299dd54c435a.php` before `engine/lib/upgrades/2016101400-3.0.0-security-defaults-1f79acd51ba4560f.php`.

Otherwise the used code doesn't match the database schema.

Master is dev branch, so I guess we can simply re-create or rename the latter one.

**Comment by jdalsem** [comment]
yep... thought of the same solution... will make a PR for it soon

**Comment by mrclay** [comment]
PR #10599

**Comment by jdalsem** [comment]
Fixed as part of #10560
