### ISSUE TITLE
User delete causes owned metadata/annotation deletes

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10636]
While it's makes good sense to delete the user's content, and MD/annotations on that content, it's not clear that the default behavior should be to also delete MD/annotations on *other* content.

We [started deleting owned MD/annotations](https://github.com/Elgg/Elgg/commit/8b5fd806d6871aaeb179376328a8af215ed44f88) for 1.6, because comments (which were then annotations) were being left over and causing problems.

Now that we'd like to move 2nd entity attributes to metadata (#10629), this poses some danger. A user can update an entity's attribute (now stored as MD) and if that user is deleted, the entity attribute will be deleted too.

My preferred solution would be to strip metadata specifically down to simply a key-value store, no access control (already a goal) but also no owner. With this change, an entity's attributes would not be in danger of deletion depending on who last touched them.

**Comment by jdalsem** [comment]
Making the choice for removing owner would make #10629 a whole lot easier... what do other @elgg/core members think of this?

Personally i would like to keep at least time_created on the metadata, but otherwise the rest can be removed. We do need to investigate some real life cases to see if metadata owners differ from metadata entity owners and why...

**Comment by hypeJunction** [comment]
I am fine turning metadata in a key/value store, and moving all other more complex use cases (incl. time sensitive values) to annotations.

**Comment by beck24** [comment]
makes sense to me
