### ISSUE TITLE
Cast metadata silently

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10749]
**UPDATE:** By vote we decided to explain the MD casting strategy in the docs and cast values as necessary without any logging.

---

@Elgg/contributors @Elgg/core [Currently](https://github.com/Elgg/Elgg/blob/2.3.0/engine/lib/extender.php#L21) the metadata/annotations system only returns integers if the value set was an integer, and all other types are cast to string. If the set value isn't numeric (e.g. bool), a warning is issued, but the message doesn't tell you the name of the metadata.

Please vote for one of the following:

**1.** When logging the cast, add the metadata/annotation name to the message, and reduce the log level to NOTICE.
**2.** Always cast silently.

In both cases we should explain the casting strategy in the docs.

More background discussion: #10186, #10739

**Comment by hypeJunction** [comment]
1

**Comment by mrclay** [comment]
2. If docs are made more complete, I'm actually OK with silent casting.

**Comment by jdalsem** [comment]
2: this has been the case before #10186, i am open for option 1, but only for 3.x

**Comment by jeabakker** [comment]
2

maybe for 3.x add `boolean` as a supported type

**Comment by beck24** [comment]
1

**Comment by iionly** [comment]
With https://github.com/Elgg/Elgg/pull/10788 not merged what is the plan for the 2.3 branch now? The constant warnings due to the saving of bool metadata by the site_notification plugin is so annoying. And even with 3.0 released the 2.3 branch will become the LTS branch for at least a year.

So, cast silently again without deprecating anything or fix site_notifications to not save a boolean value (https://github.com/Elgg/Elgg/pull/10739)?

**Comment by mrclay** [comment]
I reopened #10788.
