### ISSUE TITLE
Twitter API removal strategy

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#10799]
We need too loose Twitter API from core, it's a half-baked plugin, which really messes up data integrity. We need a strategy for it's removal - unfortunately users registered with Twitter do not have emails, so we can't just throw it out and tell them to use password reset... I suppose we could keep it around and only allow previously registered users to use it. Once they logic we require that they provide the email.

**Comment by iionly** [comment]
I think the first step might be to no longer allow creating new accounts with Twitter credentials. I don't see the necessity of it anyway. If someone wants to join the community site for a reason he won't be stopped by the need of creating a regular account with an email address provided. I also suspect since a while that the possibility of creating an account with Twitter data without email validation is misused on the community site by spammers.

Is is possible to find out how many accounts have been created with the Twitter sign in option? And how many of them have ever really been used to post at least a single content item (discussion topic, comment, etc.) NOT taking into account any profile spam? And after not taking into account all these non-used accounts how many accounts are still in use, i.e. user logged in at least once say in the last 2 years? Getting rid of the Twitter API plugin on the community site could be done in the hard way by removing at least the inactive and non-used accounts (possibly cleaning up a lot of profle spam then, too). Or it could be done in a soft way by just letting the accounts stay without the users being able to log in anymore if they haven't provided an email address to reset the password. Whatever approach taken it could get announced a few months before any action is taken (maybe also prompt any user who has no email address saved to do so on login during that period). Any account still without email adress will then either get removed (maybe limited to accounts without any content posted) or just be left dead (maybe the user can ask for an email address to be added by admin to reactivate the account then).

**Comment by mrclay** [comment]
#10875 would allow elgg.org to turn off new Twitter registrations completely, though we either would have to release a new feature on 2.3 or put this feature only in a separate repo.

**Comment by cleverthings** [comment]
I only use the Twitter API to send user posts from the wire to their Twitter feed. Users seem to like that feature, but I can see the argument that it shouldn't be part of core. So do you want any bugfixes for it - or would that be a waste of our time?  I had to heavily refactor my code including core, so I can't really push/pull now. Before you yell at me:  I have physical disabilities, so every click and whitespace scroll I eliminate is a big help for me. Nothing wrong with your code!  Anyway, I did make a few changes to twitter_api.php changing the three lines from
 forward('settings/plugins', 'twitter_api');
to
        forward('settings/plugins/' . elgg_get_logged_in_user_entity()->username . '/twitter_api', 'twitter_api');

And for posts that exceed >140 characters, I was going to replace with a link back to the post instead of truncating the text.  What do y'all think about something like this in start.php at the end of the twitter_api_tweet function:
  if (iconv_strlen($params['message']) < 141) {
        $api->post('statuses/update', array('status' => $params['message']));
    } else {
         // replace message with translation string text plus link
        $api->post('statuses/update', array('status' => "I posted to the wire: " + $params['url']));
    }

**Comment by hypeJunction** [comment]
The plugin will still exist in some form, so I am sure bugfixes will be appreciated even if the plugin moves to its own repository

**Comment by jdalsem** [comment]
The plugin has been moved to elgg/twitter_api and will not come bundled in future releases

**Comment by hypeJunction** [comment]
Well, it has been removed, but it doesn't solve the problem. When we upgrade the community to 3.0, all those users with twitter login won't be able to either login or reset their password, because there is no email on record.

**Comment by jdalsem** [comment]
that is a problem that needs to be solved by the sysadmin of the elgg community :)

**Comment by hypeJunction** [comment]
We shipped Elgg with faulty plugin, how is it sysadmin's problem?

**Comment by jdalsem** [comment]
is it faulty in 2.3? that is not what this ticket is about.. if there is something wrong in 2.3 with this plugin we should fix it.

**Comment by hypeJunction** [comment]
It creates user entities without an email, which is fundamentally out of sync with Elgg's data model

**Comment by jdalsem** [comment]
this ticket was about removal strategy... there is no open issue that reports the missing email data for twitter registered users AFAICT. You could open one... But nothing in Elgg enforces users to have an email. That you are missing one is only unfortunate. Changing that can be considered a feature.

**Comment by iionly** [comment]
@jdalsem sorry, but I think this issue here IS/WAS addressing the problem with missing email and passwords for twitter users that would become a problem when twitter_api plugin is no longer available. This issue was not about the removal of the twitter_api plugin but rather about the follow up strategy that becomes necessary when doing so. So, I think it's not a matter of opening a new issue but I would rather say this issue here is unresolved. At least unresolved if you take into account that the Elgg community site becomes affected when updating to 3.0.

**Comment by jdalsem** [comment]
There is only a problem when a plugin is no longer functioning. Even on Elgg 3.0 the twitter_api could still function as is AFAIK. There is however a problem if you want to get rid of the plugin in your site and you want the users to be notified on that. That is a problem you are already having for multiple years because those users could not be notified in any way (other than on site).

So for Elgg 3.0 you could still use the twitter api plugin (as long as it works).

OR

Decide a strategy for removal, but that is a sys/community admin task and not something for core Elgg development.

These issues are not meant to keep track of issues related to the management of the Elgg community. We have other repos for that. That is why i closed this ticket here.

**Comment by mrclay** [comment]
Let's move discussions to https://github.com/Elgg/twitter_api/ and https://github.com/Elgg/www.elgg.org/issues. I opened https://github.com/Elgg/twitter_api/issues/1 because the API plugin needs to be able to allow logging in without create new accounts from Twitter. Any migration solution is going to be somewhat site-specific, but let's try to share solutions we come up with.
