### ISSUE TITLE
2.3: detect/reject emoji without dumping an exception

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10980]
Until 3.0, there should be better UX for this.

FYI https://stackoverflow.com/a/24672780

**Comment by cleverthings** [comment]
I saw a previous ticket "utf8mb4 and database creation #6072" where it looks like emoji support was added to the elgg database in v1.9.  I guess to filter them out would be by adding a line to thewire/start.php save or filter function.  Which direction are y'all leaning towards for v3.0 - supporting them or rejecting them by filtering them out? Are there any major obstacles to supporting them (other than the obvious resources/available time factor)?

**Comment by beck24** [comment]
It's 2017, we shouldn't be rejecting emojis

**Comment by mrclay** [comment]
New 3.0 sites use/require utf8mb4, but there's no change upgrading from 2.3. https://github.com/Elgg/Elgg/commit/5e75e7cfe3c597faff2b587fa281e5415ae2b349

**Comment by beck24** [comment]
ah, I see

**Comment by cleverthings** [comment]
Core devs probably already knew the answers, but since I'm just learning elgg I checked all of the fields in core 2.3.3 to see where this is a problem. If this info doesn't help with a fix, I thought it might at least help in testing the fix later.
***************************
THE_WIRE:
An exception occurred while executing 'INSERT INTO elgg_metastrings (string) VALUES (?)' with params ["Have a great day!\ud83d\ude0d"]:
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x8D' for column 'string' at row 1
QUERY: INSERT INTO elgg_metastrings (string) VALUES (:string)
***************************
BLOG (title, excerpt, body, tags):
title:
An exception occurred while executing 'INSERT INTO elgg_objects_entity (guid, title, description) VALUES (?, ?, ?)' with params [423, "", "Have a great day!\ud83d\ude0d\r\n"]:
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x8D\x0D\x0A...' for column 'description' at row 1
INSERT INTO elgg_objects_entity (guid, title, description)

excerpt:
QUERY: INSERT INTO elgg_metastrings (string)

body:
INSERT INTO elgg_objects_entity (guid, title, description)

tags:
INSERT INTO elgg_metastrings (string)
***************************
BOOKMARKS (tags, description):
tags: gives error, but tells to check title and address.
description: gives error, but tells to check title and address.

title: gives proper error.
address: gives proper error.
***************************
PAGES (page title, page text, tags):
title: INSERT INTO elgg_objects_entity (guid, title, description)
text: INSERT INTO elgg_objects_entity (guid, title, description)
tags: INSERT INTO elgg_metastrings (string)
***************************
FILES (title, description, tags):
title: INSERT INTO elgg_objects_entity (guid, title, description)
description: INSERT INTO elgg_objects_entity (guid, title, description)
tags: INSERT INTO elgg_metastrings (string)
***************************
GROUPS (group name, description, brief description, tags):
group name: INSERT into elgg_groups_entity (guid, name, description)
description: INSERT into elgg_groups_entity (guid, name, description)
brief description: INSERT INTO elgg_metastrings (string)
tags: INSERT INTO elgg_metastrings (string)
***************************
PROFILE:
Display Name: UPDATE elgg_users_entity SET name=
About Me: INSERT INTO elgg_metastrings (string)
brief description: INSERT INTO elgg_metastrings (string)
location: INSERT INTO elgg_metastrings (string)
interests: INSERT INTO elgg_metastrings (string)
skills: INSERT INTO elgg_metastrings (string)
Contact Email: catches it before @ but not after, then mangles URL.
phone: INSERT INTO elgg_metastrings (string)
mobile phone: INSERT INTO elgg_metastrings (string)
website: INSERT INTO elgg_metastrings (string)
twitter: INSERT INTO elgg_metastrings (string)
***************************
SETTINGS:
User Name: UPDATE elgg_users_entity SET name
Email: catches it before @ but not after, then mangles URL.
Change Password: accepted them, now let's see if I can log in with them.
***************************
INBOX: Compose a Message:
to: retest once user names have emojis in them.
subject: INSERT INTO elgg_objects_entity (guid, title, description)
body: INSERT INTO elgg_objects_entity (guid, title, description)
***************************
ADMIN Create User:
username: INSERT into elgg_users_entity (guid, name, username, password, salt, password_hash, email, language)
display name: INSERT into elgg_users_entity (guid, name, username, password, salt, password_hash, email, language)
***************************
SEARCH: works! at least seems to, but will retest once there are some emojis to search for...
***************************
MEMBERS: search works! at least seems to, but will retest once there are some emojis to search for...
***************************

**Comment by jdalsem** [comment]
Not going to do anything with this
