### ISSUE TITLE
add features from arckinteractive/image_orientation into core image manipulation

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#10990]
https://github.com/arckinteractive/image_orientation

**Comment by hypeJunction** [comment]
Imagine is part of core and it should be pretty easy to do withing the Uploads service.

**Comment by jdalsem** [comment]
thought the same... it only adds some extra server requirements (or the feature should sniff the existence of the feature)

**Comment by hypeJunction** [comment]
Now we just need a volunteer to do it :)

**Comment by iionly** [comment]
I thought image orientation correction would already be in core.

Seems I thought wrong:

I found

https://github.com/Elgg/Elgg/pull/6560
https://github.com/Elgg/Elgg/pull/6385
https://github.com/Elgg/Elgg/pull/6592

All closed without being merged. Maybe that's why @beck24 created the plugin instead.

Still open

https://github.com/Elgg/Elgg/issues/10280.

**Comment by jdalsem** [comment]
Closing as it is a duplicate of #10280
