### ISSUE TITLE
Views should not be setting http headers

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#11178]
Strawman:
Resolve content type headers from viewtype and trigger a hook to populate the rest. Do this in response factory

**Comment by jeabakker** [comment]
Views should not set headers.
Resources are special views and should be allowed to set headers as there is no easy way to do this otherwise. Auto detection could introduce new issues.
Controllers can set the correct headers in their responses.

Currently the only views that set headers are the page wrappers.
