### ISSUE TITLE
Create default widgets on first login

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11243]
Now the default widgets are created when the account is created. If you have a site with spam problems for all (unvalidated) users the default widgets are created.

This adds useless data to the database.

If we move the creation of the default widgets to the first login, we get less pollution in the database

**Comment by mrclay** [comment]
SGTM

**Comment by jdalsem** [comment]
first login is not good... other user may need to see the widgets on a valid users profile. We need a `$user->validate` process similar to the pam_handler where multiple hooks can prevent validation of a user. When no hook prevents validation the user is validated which triggers an event. That event is the best way for default widgets to be created.

**Comment by hypeJunction** [comment]
I think I added the event to core already

**Comment by jdalsem** [comment]
this can be done later... not a blocker for the 3.0 beta release... like to still fix this for 3.0 though

**Comment by jdalsem** [comment]
Pushed this back on the milestones because we have no consistent way to solve this at this moment. We need to look into adding a mechanisme where the 'validated' event is happening in a consisten way. 

Alternatively we can also look into adding default widgets at the moment when the widget layout is drawn for the first time.
