### ISSUE TITLE
Cleanup duplicate tests in simple test

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11256]
It looks like a lot of tests are duplicate available in phpunit and in simpletest.... @hypeJunction can you explain if this is true and why this is the case? Did you mean to clean this up after your latest test changes?

**Comment by hypeJunction** [comment]
I left simpletests behind for now to be on the safe side. PHPUnit integration tests are in their early days, so there may still be corks to be addressed. Simpletests are there as a back up until we are confident enough to remove them. 
I imagine the reason you are asking is the double amount of work that goes into maintaining them. I would say verify that PHPUnit test does what it should, and remove simpletest. Because the migration was done in bulk, I couldn't verify each individual test, but after a set of fresh eyes, it should be ok to remove simpletests one by one

**Comment by jdalsem** [comment]
This will happen when we touch the tests
