### ISSUE TITLE
Fail to install on Azure

### ISSUE THREAD

**Issue by JCKodel** [Elgg/Elgg#11351]
Trying to install on Azure using free hosting.
There is an option to use MySQL in-app (in the same "machine" webserver is installed).
Works fine for WordPress, but while trying to configure elgg:

![image](https://user-images.githubusercontent.com/379339/32303008-0df0e2b0-bf4d-11e7-85b9-36fbef7eef82.png)

Fatal error: Interface 'Throwable' not found in D:\home\site\wwwroot\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\DriverException.php on line 33

(the host, user and port are provided by Azure, so, I know everything is working as intended).

The idea is to test it and, if suits our needs, then deploy it on a non-free server and separated mysql instance.

Can anyone help me with some clue about what it is wrong?

**Comment by iionly** [comment]
Have you created settings.php in the elgg-config folder yourself before starting the installation? Or could it be that the elgg-config folder has no write permissions (777 only during installation) to allow Elgg the creation of settings.php during the installation?

**Comment by jeabakker** [comment]
`Fatal error: Interface 'Throwable' not found in.....` is caused by a PHP version requirement which isn't met. `Throwable` is provided by PHP7 if you use PHP5.6 this can cause errors.

Which version of Elgg are you trying to install? And how are you getting Elgg, from the website https://elgg.org/about/download

**Comment by iionly** [comment]
FYI, I also had this error when trying to install Elgg 2.3.4 (zip from the community site). Server has PHP 5.6. I think I got this error only because I had created settings.php manually. Without settings.php created before the installation it worked. Or it might have been the permissions of the elgg-config folder. I had no time to test what exactly caused the error. That's why I asked @JCKodel if either of these two possible causes might also be the reason the installation fails for him.

**Comment by JCKodel** [comment]
@iionly: I just uploaded the contents of zip downloaded from the site.

@jeabakker: The Elgg version is the latest available to download in the site. PHP is version 5.7 (Azure allows me to choose from 5.6 to 7.something)

@iionly: In this case, all I have is an ftp to upload files, I don't have any kind of server access (is a PaaS option: a web server as a service). I just tried to upload the files and start up the installation =) Azure provides us with a IIS server with a local MySQL integrated (and a PhpMyAdmin installed).

As I needed this fast to show to some folks at my company, I installed it on a Ubuntu virtual machine and that worked just fine.

It would be nice if someone with more PHP experience could check how to use Azure PaaS to deploy this (it's free for a basic web site with MySQL and 10Gb).

There is also one-click setups for a lot of good products out there (example: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/MonoSoftware.MonoX?tab=Overview)

**Comment by iionly** [comment]
Sorry. But I won't go as far as to test this myself on Azure.

Elgg 2.x uses the PDO php extension to connect to the database. Maybe this extension is not installed on your server or there might be some configuration necessary for the server to connect to the database using PDO-php and not MYSQL-php. I can't say for sure if this explains the error you see.

I came across the same error message for another reason (settings.php existing already when starting the installation) - https://github.com/Elgg/Elgg/issues/11361. And in this case the error occurs already when starting the installation and not later in step 3.

**Comment by jeabakker** [comment]
I released 2.3.5 today (which was build correctly) and i also fixed the download of 2.3.4.

Could you please try again

**Comment by jdalsem** [comment]
@JCKodel do you have some more intel on this?

**Comment by jdalsem** [comment]
I guess we can assume by now this has become a stale ticket.
