### ISSUE TITLE
reverse_order_by not working for default order by

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11460]
if no `order_by` is passed to elgg_get_entities, passing `reverse_order_by` has no effect

default order is 'time_created DESC', `reverse_order_by` should change this to 'time_created ASC'

**Comment by hypeJunction** [comment]
To keep legacy options generic I removed default orders. 
Just read `reverse_order_by` here then: https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/Database/Entities.php#L133

**Comment by jdalsem** [comment]
hmm... don't get it... is reversing applied after adding the default? or before?

**Comment by hypeJunction** [comment]
If `order_by` is set, it's normalized https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/Database/LegacyQueryOptionsAdapter.php#L933
If not set, we use `e.time_created desc`, but instead of default to `desc` we need to check `reverse_order_by`.

The whole `reverse_order_by` deal needs to go away. I have never used it and it's a mind twister, and has random effects on all other orders.

**Comment by jdalsem** [comment]
We could remove it in core and just mention it in the upgrade docs... i see no need for it.

**Comment by mrclay** [comment]
FYI it's used 7 places in core. Notably, to find the latest page content.

**Comment by mrclay** [comment]
PR #11480
