### ISSUE TITLE
Error during tests about routes

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11607]
example https://travis-ci.org/Elgg/Elgg/jobs/330275203#L904

` ERROR: Unable to generate a URL for the named route "default:river" as such route does not exist.`

I think plugin routes are not registed?

**Comment by jeabakker** [comment]
thoughts @hypeJunction

**Comment by hypeJunction** [comment]
Not sure offhand.

**Comment by hypeJunction** [comment]
I think what's happening is that the router is being reset in one of the tests, but routes don't get reregistered. I think we should put route registerations into a `init, system` handler, so that they get stored in setups and reregistered on each boot.

**Comment by hypeJunction** [comment]
So, the problem is that we require setup files once and store them in Application, and run all the setups whenever an application is booted. That doesn't take into account what plugins are active at the time the test runs (which in case of unit test is none). 
I am leaning more and more towards being able define active plugins via config. It would save a lot of hassle during development, so I am not going to spend time trying to fix this particular issue.

**Comment by hypeJunction** [comment]
Can be closed
