### ISSUE TITLE
2.3: get_entities_From_metadata adds order by related joins even if count is true

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11806]
the order by clause later is dropped, but the join is still intact (for metadata this create 3 useless joins)

**Comment by jeabakker** [comment]
As `order_by_metadata` still needs to validate that the entity has the metadata name it needs at least 2 joins. So we could save 1 join (metadata value).

The effort to get the required information to the correct functions is probably more work that the gain will be.

In Elgg 3.0 since we already dropped `metastrings` and the `QueryBuilder` is smarter this will undo any effort we put into this.

Not going to put effort into this
