### ISSUE TITLE
/cache/* return 404 on Nginx

### ISSUE THREAD

**Issue by wangnguyen** [Elgg/Elgg#11914]
Hi Elgg team, I have an issues when I try installing Elgg on my Nginx server (php7).
I can't get css, js files. Web just show same layout with any url (my local is working well). Please check the screenshot below
https://drive.google.com/file/d/1O9emBhDGcAUYIOXhioud4LnPc5SI8OTh/view?usp=sharing

thank you so much,

**Comment by jeabakker** [comment]
Please give us a little bit more information

- Which version of Elgg are you using
- How did you get Elgg (zip from elgg.org, composer installed, git pull)
- have you looked at http://learn.elgg.org/en/stable/appendix/faqs.html#css-is-missing

**Comment by jdalsem** [comment]
Closing due to lack of feedback

**Comment by AkashicSeer** [comment]
I was having this issue with version 4.3.2. My Nginx config was wrong. So I re-read the install docs and it mentions an install folder, but not where it is located

> On Nginx server copy install/config/nginx.dist to /etc/nginx/sites-enabled and adjust it’s contents

This is actually in vendor/elgg/elgg/install/config/nginx.dist

I changed that configuration up since I don't have fastcgi installed I use fpm instead. It seems so far elgg works with php8.1
Here is the configuration for Nginx I finally got working with php8.1-fpm instead of FastCgi. While FastCgi is more secure it uses more resources and is slower.
	location ~ \.php$ {
	try_files $uri @elgg;
	fastcgi_index index.php;
	#NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        include fastcgi.conf;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_intercept_errors on;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	location @elgg {
		fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
		include /etc/nginx/fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root/index.php;
		fastcgi_param SCRIPT_NAME     /index.php;
	}

**Comment by jeabakker** [comment]
@AkashicSeer thank you for sharing
