### ISSUE TITLE
investigate widget upgrade errors

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11933]
https://github.com/Elgg/Elgg/pull/11924#issuecomment-383296568

**Comment by hypeJunction** [comment]
They are not widget errors per se. On travis, widgets tests run before cli tests, so for some reason the status of the logger overflows into the cli tests (widget tests actually expect errors). My guess is that because the console output is shared, the errors are not flushed. Need to perhaps manually close logger handlers.

**Comment by hypeJunction** [comment]
This fixed it
https://github.com/Elgg/Elgg/pull/11924/files#diff-3a567de1551782888f9086b3e8903897R114

**Comment by jdalsem** [comment]
Fixed as part of https://github.com/Elgg/Elgg/pull/11924/commits/fb5b0d6b1eccd86ff56243245bde6599128b64fe
