### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by QzAmoy** [Elgg/Elgg#12151]
after installed i got 500 error
[13-Aug-2018 09:07:40 UTC] Exception at time 1534151260: InstallationException: Unable to handle this request. This site is not configured or the database is down. in /Users/qz/Documents/myProject/elgg-2.3.8/www/vendor/elgg/elgg/engine/classes/Elgg/BootData.php:84
Stack trace:
#0 /Users/qz/Documents/myProject/elgg-2.3.8/www/vendor/elgg/elgg/engine/classes/Elgg/BootService.php(207): Elgg\BootData->populate(Object(stdClass), Object(Elgg\Database), Object(Elgg\Database\EntityTable), Object(Elgg\Database\Plugins))
#1 /Users/qz/Documents/myProject/elgg-2.3.8/www/vendor/elgg/elgg/engine/classes/Elgg/BootService.php(93): Elgg\BootService->getBootData(Object(stdClass), Object(Elgg\Database))
#2 /Users/qz/Documents/myProject/elgg-2.3.8/www/vendor/elgg/elgg/engine/lib/elgglib.php(2196): Elgg\BootService->boot()
#3 [internal function]: Elgg\Application->{closure}('boot', 'system', NULL)
#4 /Users/qz/Documents/myProject/elgg-2.3.8/www/vendor/elgg/elgg/engine/classes/Elgg/EventsService.php(113): call_user_func_array(Object(Closure), Array)
#5 /Users/qz/Documents/myProject/elgg-2.3.8/www/vendor/elgg/elgg/engine/classes/Elgg/Application.php(267): Elgg\EventsService->trigger('boot', 'system')
#6 /Users/qz/Documents/myProject/elgg-2.3.8/www/vendor/elgg/elgg/engine/classes/Elgg/Application.php(431): Elgg\Application->bootCore()
#7 /Users/qz/Documents/myProject/elgg-2.3.8/www/vendor/elgg/elgg/engine/classes/Elgg/Application.php(384): Elgg\Application->run()
#8 /Users/qz/Documents/myProject/elgg-2.3.8/www/index.php(8): Elgg\Application::index()
#9 {main}

**Comment by iionly** [comment]
"This site is not configured or the database is down."

What do you mean with "after installation"? Have you gone through the install process (site.url/install.php) or have you only created the file elgg-config/settings.php manually? In case of the latter you still need to go through the install process to initialize the database and to make some configurations like setting site url and creating the admin account. If you have gone through the install process, are the database connection details in settings.php correct?

I think your problem is not due to a bug but rather something has not be done right during the installation process. The community site might be the better place to sort out install problems.

**Comment by jdalsem** [comment]
Please look at the suggestions by @iionly . If you have more details regarding this issue let me know and i will reopen.
