### ISSUE TITLE
Elgg3x: Uniformity needed in readable Text width across all pages.

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#12260]
Core Elgg 3x has mainly the following readable pages:
Blog post page or Blog content
Bookmarks
Files page (view-able content)
Groups
Wire
Activity 
All the pages have approximate 900 px width ( as seen is desktop browser windows) of readable matter EXCEPT the Activity page, which adds another 300 px (approx measurements, not exact) . Uniformity in text width areas will improve usabilty.

**Comment by jdalsem** [comment]
There is uniformity based on elements present on the page. The activity is wider because there is no sidebar. There are multiple pages without a sidebar.

If you need uniformity for a max-width for the main content, you can add simple css to achieve this. I personally do think that activity and blog content are the same type of 'content'
