### ISSUE TITLE
Elgg 3: tedivm/stash error after installed elgg

### ISSUE THREAD

**Issue by gnh1201** [Elgg/Elgg#12289]
tedivm/stash error after installed elgg

[Thu Nov 29 02:59:54.594080 2018] [php7:error] [pid 31456] [client 10.0.0.1:59142] PHP Fatal error:  APCuIterator::__construct(): Could not compile regular expression: [59a67bbbc2bd7f9831640aec7821d146::59a67bbbc2bd7f9831640aec7821d146::sp::stash_default::dic::di\\definition\\group_tools::*] in /home/catswords/www/vendor/tedivm/stash/src/Stash/Driver/Apc.php on line 123
[Thu Nov 29 02:59:54.969407 2018] [php7:error] [pid 30552] [client 10.0.0.1:59288] PHP Fatal error:  APCuIterator::__construct(): Could not compile regular expression: [59a67bbbc2bd7f9831640aec7821d146::59a67bbbc2bd7f9831640aec7821d146::sp::stash_default::dic::di\\definition\\group_tools::*] in /home/catswords/www/vendor/tedivm/stash/src/Stash/Driver/Apc.php on line 123

**Comment by gnh1201** [comment]
As a temporary measure, I disabled the cache clear function as a comment.
However, this is a bug and should be resolved because the cache is not cleared.

**Comment by jdalsem** [comment]
How did you install? Downloaded a zip package? Or installed via composer? What is your PHP version?

**Comment by gnh1201** [comment]
PHP 7.2, I was download zip from 3.x git branch, and I installed elgg via composer.

**Comment by RiverVanRain** [comment]
I guess there was a wrong installation. 
It isn't an Elgg bug so I think this issue should be closed.
Same on #12290

**Comment by gnh1201** [comment]
Elgg does works well all. without 2 issues.
I think it is not wrong installation. I will find how to fix, soon.

**Comment by gnh1201** [comment]
This error is currently not appearing on my site.
However, it is clear that this is an error that interferes with the installation process.
If the above error does not work, you can temporarily use the following method.

1. edit /vendor/tedivm/stash/src/Stash/Driver/Apc.php (nearby line 123)

```
    /**
     * {@inheritdoc}
     */
    public function clear($key = null)
    {
        return true;  // *********** LIKE THIS **************

        if/vendor/tedivm/stash/src/Stash/Driver/Apc.php (!isset($key)) {
            return $this->apcu ? apcu_clear_cache() : apc_clear_cache('user');
        } else {
            $keyRegex = '[' . $this->makeKey($key) . '*]';
            $chunkSize = isset($this->chunkSize) && is_numeric($this->chunkSize) ? $this->chunkSize : 100;

            do {
                $emptyIterator = true;
                $it = $this->apcu ? new \APCUIterator($keyRegex, \APC_ITER_KEY, $chunkSize) : new \APCIterator('user', $keyRegex, \APC_IT$

                foreach ($it as $item) {
                    $emptyIterator = false;
                    $this->apcu ? apcu_delete($item['key']) : apc_delete($item['key']);
                }
            } while (!$emptyIterator);
        }

        return true;
    }
```

2. run clear cache on administrator page.

3. remove `return true;` in /vendor/tedivm/stash/src/Stash/Driver/Apc.php (nearby line 123)

**Comment by gnh1201** [comment]
The effect of this problem is that not all operations that require flush_cache will work.
I have not been able to find a concrete way to solve this problem.

**Comment by Facyla** [comment]
I have the same issue on latest Elgg 3.1.3, even with latest Stash version which did not solved the issue for me. 
Config : Ubuntu 18.04 / PHP 7.2 / nginx
More details in my comment on https://elgg.org/discussion/view/2902661/apcuiteratorcould-not-compile-regular-expression#elgg-object-2970819

**Comment by Facyla** [comment]
Other useful log extracts on PHP 7.2: 
- PHP message: Compilation failed: PCRE does not support \\L, \\l, \{name}, \\U, or \\u at offset 106
- Regex string: [410dddb3a669b6e51a8398f10329061f::410dddb3a669b6e51a8398f10329061f::sp::stash_default::dic::di\\definition\\logger::*]
- Faulty string part: "\\logger" matches \\l deprecated selector

I suspected some change between PCRE regex between PHP versions: in PHP 7.2 phpinfo tells the PCRE Library Version : 8.43 2019-02-23

Then i tested the same Elgg install (without any other change) with PHP 7.1 and 7.3 : 
- 7.1 : "Fatal error in exception handler. Check log for Exception at time 1569416762"  // phpinfo details : PCRE Library Version | 8.43 2019-02-23
- 7.3 : runs without any warning :+1:   phpinfo details : PCRE Library Version | 10.33 2019-04-16

=> it seems this error is caused by incompatible PCRE regex syntax between versions of PHP7, namely 7.3 vs (7.1 and 7.2). 

Maybe a version check would help?  I'm not sure whether it should be on Elgg side, or on tedivm Stash side: any advice?
