### ISSUE TITLE
Elgg 2.3: manifest.json not always accessible with walled-garden option enabled

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#12406]
Problem described at https://elgg.org/discussion/view/2888913/problem-after-putting-the-site-online might be due to manifest.json access blocked with walled-garden option enabled.

I tried to reproduce the problem but I got some strange result. I tested on two test installations on the same server with the same browser. It worked on one test installation (Elgg 2.3.8) and failed on another (Elgg 2.3.10). Not sure if the difference in the version explains why it failed on the (newer) test installation.

Anyway, adding manifest\.json as allowed public page seemed to have fixed the issue with access on walled-garden sites.

**Comment by jeabakker** [comment]
![image](https://user-images.githubusercontent.com/881958/55335175-f003fa00-549a-11e9-9c33-a2bf4f73ede1.png)

On the image you can see the requested url comes from some plugin /social/manifest.json if this is a page_handler than the plugin should maybe support walled garden mode, I don't know if it is needed or intended.
This doesn't look like a problem in core as this is in some plugin.

The rewrite rules of Elgg state if it's a file on the server, serve it, otherwise start Elgg and see if it's a page_handler and serve the request (with all access limitation, like walled garden applied).

**Comment by iionly** [comment]
@jeabakker there's one usage in Elgg core. See https://github.com/Elgg/Elgg/blob/52c01aa5d46d6272825706bda88e980c3a60e698/engine/lib/elgglib.php#L2025 for the Elgg 2.x branch and https://github.com/Elgg/Elgg/blob/72e57ac100ff446302b422887016e89d8687ffb9/engine/lib/elgglib.php#L1571 in the 3.x branch. I also hadn't tested with any plugin that would add a manifest.json on its own and got a problem when explicitely trying to access the file. I don't know when the manifest.json file is used in general. It might be a mobile browser thing mostly. Reopen?

**Comment by jeabakker** [comment]
thanks for pointing this out
