### ISSUE TITLE
MySQL database passwords containing apostrophes

### ISSUE THREAD

**Issue by nicolesharp100** [Elgg/Elgg#12657]
There is a bug that causes the installation of Elgg 2.3.12 LTS to fail if the MySQL database password contains an apostrophe (< ' >).  The following error is given:

"An unrecoverable error has occurred and has been logged.  If you are the site administrator check your settings file, otherwise contact the site administrator with the following information:	Exception at time 1559661348."

**Comment by rohit1290** [comment]
It will be helpful if you share the actual log. 1559661348 is just the linux timestamp. 
Please share the error from your error_log file.

**Comment by rohit1290** [comment]
The single apostrophe i.e., `'`  is generating the error because the password is wraped around the single apostrophe and the password string is breaking in between because of this.
https://github.com/Elgg/Elgg/blob/edb87a0180eb129e21dd3db0556342f73dc5d318/elgg-config/settings.example.php#L62

What you can do is, replace the single apostrophe with double quote. Your config file should now look like this:
`$CONFIG->dbpass = "{{dbpassword}}";`

**Comment by nicolesharp100** [comment]
Not sure where to find the error log.  I was just using the web installer.  I use a random password generator, so sometimes there are apostrophes and sometimes there aren't.  The installation worked when I used a random password without an apostrophe.  I figured if the password is being saved in PHP it might be breaking the syntax if there's an apostrophe in the password.  I think there is a way to prevent that, but that's outside of my skill set.  I just figured it should be reported.  It would be more helpful though if the error message specifically told the user that the installation failed because the database password contained an apostrophe.  Not all users might be able to understand that an apostrophe could be the cause of the installation failure.  I might not have figured it out myself if I had not already done a successful test installation using a different random password without an apostrophe.
