### ISSUE TITLE
Elgg 3.3.0: Validation username failure

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#13067]
An error occurs by changing the username and using non-latin characters.
User doesn't have access to many pages on the site after this changing.

Discussion on Community: https://elgg.org/discussion/view/2996848/cannot-publish-blog-post-unicode-incompatibility-with-elgg-330

**Comment by RiverVanRain** [comment]
Can we force to use of a whitelist instead of blacklist?

```
//Don't use non-latin and digitals
$whitelist = '/^([A-Za-z_0-9]+)$/i';
```

**Comment by jeabakker** [comment]
we made some changes to mb_wrapper functions in #13042 maybe that caused it.
Also i remember an issue (but cant find it currently) with unicode characters. Maybe since we changed to support more mb_wrapper functions no we encounter a problem further in the system.

We tried to reproduce the problem but since we don't know how to correctly generate other (non-latin) charaters there is now way to test this.
If someone could maybe write a test that proves the issue we can try to fix it

**Comment by RiverVanRain** [comment]
My opinion is a bad practice to use unusual or control characters: proc␀ess␠thisäifÄuÜc'aÖn;ü in the usernames.

We may come across a variety of ways to write a username. 
In addition, there is a high probability that the security of the entire site will be affected.

Just one quote from SO:

> The "well-designed system" may some day meet real-world integration and security cases. Domain names, emails, file names and other systems that have their restrictions. There are a lot of security issues with [Unicode usernames](http://unicode.org/reports/tr36/), as demonstrated by [Spotify](https://labs.spotify.com/2013/06/18/creative-usernames/) that might have thought the same way. To solve all these one may just follow [POSIX.1-2008](http://serverfault.com/a/578264/226737) standard for a portable username
