### ISSUE TITLE
FR: jquery legacy plugin for Elgg 4?

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#13083]
As I understand the plan is to replace jquery with something else in Elgg 4. It has also been predicted that upgrading plugins for Elgg 4 would probably mean more work also due this change.

Would it be possible to pull out all jquery related code into a plugin to provide legacy support instead of just dropping it? If someone doesn't require jquery compatibility the plugin could be kept disabled. But for others it might be useful - if only to make the upgrade workload of plugin developers a little lighter.

**Comment by jdalsem** [comment]
my guess is that we still bundle jquery, but only load on demand instead of always available... this way plugin devs who correctly use AMD modules, can just define a dependency with jquery, to be able to still work... This will however depend on how things are going to work. We might even switch to a tool that provide jquery compatible syntax like https://kenwheeler.github.io/cash/

If you rely on 'always available' (so no AMD module) jquery, then it should be relatively easy to create a plugin to provide this.

**Comment by jdalsem** [comment]
We are going to stick with jquery for Elgg 4 at this moment. jQuery an jQuery-UI have been updated to the latest versions (https://github.com/Elgg/Elgg/pull/13383). No need for any legacy plugin
