### ISSUE TITLE
In Elgg 3x, menu items configuration does not respect "none"

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13230]
admin/configure_utilities/menu_items  does not respect "none" "none" "none"
Please see how this behaves in Elgg 2x. None as expected shows "none" menu - meaning, when no menu item is wanted, it  shows NO menu item.
Elgg 3x does not show "none" or menu items cannot be reduced to one or two or three by selecting the others as none.
This may also mean from upgrade to 3x, altered menu items in 2x will fail to show as they were, when seen in 3x.

**Comment by jdalsem** [comment]
Can you explain this with some screenshots of the config and the actual behaviour?

**Comment by daniyaree** [comment]
In Elgg 2x, when I want only I menu item to be shown, it does that easily (like all other Elgg versions)
![1](https://user-images.githubusercontent.com/43325988/84024714-ff88a800-a9a7-11ea-905f-1bf895f80636.jpg)
In Elgg 3x, when I want only one (or two or three) to be shown, it does not do that. I think in upgrade site menu is lost also. Even after selecting "none" "none" etc, in actual menu, items still show up.
![2](https://user-images.githubusercontent.com/43325988/84024828-2fd04680-a9a8-11ea-9dc6-0e650b1491e7.jpg)

**Comment by jdalsem** [comment]
The behaviour change has been part of the redesign that was part of the 3.0 release. I made a change in the translation to correctly describe the correct behaviour. I also allowed themes to easily pass the max display items as a variable to the `elgg_view_menu` function.

**Comment by daniyaree** [comment]
So "none" no longer means "none" ?
How do I show 1 or 2 or 3 menu items if I wish without touching the code or adding plugins?
Please do not make "crazy" parts in the "redesign". Please roll back, imho.
I think there was NO issue asking for such confusing change either in community site or in github. Thanks.

**Comment by daniyaree** [comment]
"Unconfigured items will be added to the end of the list" - I think we do not want this. Unconfigured means we do not want that. Thats why we have not configured. I think it still adds or does not minimize the confusion.  If have not configured : why should it be at all shown in the list?

Why we are complicating things here I really fail to understand. A finely working thing in Elgg 2x is changed to unnecessary complication ?? I really apologize again, as such things go on the top of my head ! At the same time, I thank you wholeheartedly for prompt and fast response and taking corrective measures in your own way.

**Comment by jdalsem** [comment]
> So "none" no longer means "none" ?

The 'none' just means 'none selected from the list'.

> How do I show just 1 or 2 or 3 menu items if I wish without touching the code or adding plugins?

You can not. You can only change order. The default design is suited for displaying these menu (has enough room). It will show 5 (+ more). If you need a different amount, you will need a change in theme.

> Please do not make "crazy" parts in the "redesign". Please roll back, imho.

I do not think it is crazy. Elgg 3.0 is over a year old and this has been part of that release since. Rolling back is not an option.

> I think there was NO issue asking for such confusing change either in community site or in github.

No there was not a specific wish for this change. However various improvements have been made regarding menus. This change just made a (more clear) separation between configuration of menu items and the presentation.

> PS : this jargon makes no sense to me "I also allowed themes to easily pass the max display items as a variable to the elgg_view_menu function" - is the administrative UI that used to be in 2x no longer meant to be for dumb users like me?
I apologize if I have not understood things correctly.

That comment was meant for (theme)developers.

> "Unconfigured items will be added to the end of the list" - I think we do not want this. Unconfigured means we do not want that. Thats why we have not configured. I think it still adds or does not minimize the confusion. If I have not configured : why should it be at all shown in the list?

If you have trouble understanding this... why are you not complaining the fact that the menu items are even there? For some reason you do understand the behaviour that they end up in the 'more' part...

If you want full control over the menu items in the site menu, i would advise you to use a plugin like https://github.com/ColdTrick/menu_builder

**Comment by daniyaree** [comment]
Thanks. 

> You can not. You can only change order.

but in Elgg 2x or all previous versions this could be done. There are almost no active Elgg 3x sites upgraded from 2x, that is why there has been no issues so far, imho.  When none is selected from the list, it still  means "none" = none should be shown. imho.

>  you will need a change in theme.

but due to the unilateral re-design decision, there is now no "theme" folder in Elgg also. making things too difficult unnecessarily for us.

**Comment by jdalsem** [comment]
Closing this as #13232 has been merged.
