### ISSUE TITLE
Time lag between the following items showing up and clickable action

### ISSUE THREAD

**Issue by dranii** [Elgg/Elgg#13238]
There is some unexpected time lag between the following items showing up and clickable action happening. I am not sure how to explain this but on 3G connections and some wi-fi (those which are not blazing fast) this problem can be seen more clearly. It is a problem of Elgg 3x and not 2x which probably handles this by a different means of js/css.

For example, any page in 3x loads fully - apparently all the text, pictures, contents have loaded and intuitively you click on the like icon (thumbs up icon)  OR the 3 dots at the right corner that gives you option like "edit" "delete" "subscribe" etc. Now even if the page has loaded apparently fully, and these icons are also visible, you click and nothing happens. You wait and click / re-click.

Either the things then go dumb and you have to refresh the entire page or after some time lag the desirable action gets happened - for example,  the like button becomes dark (blue) indicating you have liked or the three dots at the extreme right shows "subscribe/unsubscribe" "edit" etc
This leaves the user somewhat confused as desired action does not happen instantly and he quits without doing the intended action - in Elgg 2x this problem is not at all there. 

Same in admin, right bar nav menu - the page loads full and clicking on Users, for example, instead of giving the dropdown menu of "Add user" etc directly gets clicked and takes to the /admin page again. This is acceptable as site members are not going to use this page.

Same about CK Editor box delay - buttons appear after a time lag. This is also somewhat acceptable as I think you can start typing. Also the burger menu in 3x (as tested in mobile) does not open as soon as the page starts loading - in 2x its instant.

The main problem is with the use cases, when you click Like or the 3 dots or such stuffs, even if the page has loaded, this icons or buttons or what-do-you-call-it does not give the intended action instantly. To repeat, I am having same server configs and all fresh default installs of 3x and 2x. The problem is with 3x. Is there way to have (admin) options to use the previous js/css/whatever mechanism for these buttons at least which are shown to the end-users/site-members?

Or may be a delay added to their full appearance till they become instantly responsive to click?

I am not sure if I have been able to explain the things as I wanted to, so i any one can better frame the issue  ( and better still, a solution ) he or she is most welcome.

**Comment by RiverVanRain** [comment]
Same on #13237 - shared hosting / slow DB connection / problems with caching etc
You can check it on your localhost - no issues, right?

In the future, I recommend you ask these questions in the Community, and only after you don't get any solution open an issue here.
Please don't create an extra headache to a developers on these little things ;)

**Comment by dranii** [comment]
It happens with Elgg 3,3,6. It does not happen with Elgg 2x. Same server. Same DB connection. All configs same. Same everything except one is Elgg 3x and the other is Elgg 2x. Please note this is a problem what users from other parts of the world will experience even if I am on the fastest ded server. Slower connection means people who are having slower net connections - I mean to make the site (or Elgg) a pleasing experience for them too with fallback options or a loader icon that do not let them click things unless they are ready to act instantly. Because there is apparently a difference in how the buttons behave in 3x and 2x - some difference in js/css/whatever. These issues were first detected on localhost. If possible, can you please lead me to some good docs or tutorial that enumerates the difference in scripts/code that is behind this in Elgg 3x and 2x, may be some different library or something else is being used that is causing this.

**Comment by RiverVanRain** [comment]
Stop to copmare elgg between 2 and 3 versions - it's not correct.
Try to compare two elgg 3 instance on the different stages and post your results then.

**Comment by daniyaree** [comment]
Same problem with Elgg 3 on different webhosts. But I am not sure I have understood the solution you have suggested. Many thanks for attending this issue.

**Comment by jeabakker** [comment]
In Elgg 3 we switched a lot of JS to AMD modules. These modules are loaded a bit later in the page lifetime.
In these modules the desired effects (click gives dropdown, etc) are registered. So if a module is not yet loaded due to connection limitations the effect won't work (yet).

http://learn.elgg.org/en/stable/design/amd.html

AMD modules make it we load less JS on every page thus speeding up the page, it only loads the JS needed on that page.

The whole reason we released Elgg 3 is so we could break anything we wanted in order for ELgg te be able to grow in the future.

So as @RiverVanRain said it's not fair to compare Elgg 2 to Elgg 3, yes in Elgg 2 some things might have been faster, but less scalable en thus would introduce more problems if sites grew over time. Also more control has been given to developers in Elgg 3 to make beautiful stuff possible ;)

If you want to know what has changed between versions look at http://learn.elgg.org/en/stable/appendix/upgrade-notes.html

**Comment by daniyaree** [comment]
Elgg 3 is most welcome, and scaling is yet more welcome. I in no way mean to criticize or degrade but just want user experience and UI to be easy, as ultimately that decides user retention for a site. Thanks for explaining things nicely. It may be a good idea to have a plugin that can disable AMD and use the classic JS for those who need. Because sooner or later this will be an issue, because faster page load and scaling without letting the user take instant identifiable action would mean less "social" participation. There may be persons voicing these issues or just silently driving away to other platforms (if available) or continue to use 2x.  As I was saying in some of the posts above, can we not show the icons or show loader icons till the icons become susceptible to immediate action on click. Due to the speed increase in Elgg 3x, the visual icons load fast but they provide no visual clue to the user that nothing will happen if they click now. For example, if we could delay the burger icon in mobile view, or delay the loading of the like buttons or the 3 dot s till they happen to get loaded full for clickable action? Is it possible to add this in core? Thanks @jeabakker for valuable insight and kind words. Appreciated much.

**Comment by jdalsem** [comment]
Going to close this as there are no actionable issues here
