### ISSUE TITLE
How optimize website database

### ISSUE THREAD

**Issue by AbdulazizSobh** [Elgg/Elgg#13417]
I have a large database and this causes a problem for the hosting, how do I improve it

**Comment by gnh1201** [comment]
Maybe, you looked at the 'elgg_metadata' table. It's actually not as large as it looks. It's simply the difference between horizontal and vertical. The absolute amount of data is similar.
I want to know in detail what kind of problem you are talking about. Because important columns already have index settings, performance is unlikely to be affected.

**Comment by RiverVanRain** [comment]
@AbdulazizSobh Stop asking questions that are not related to code issues. There's [Elgg community](https://elgg.org/activity) for this.

**Comment by AbdulazizSobh** [comment]
I have a very large database of up to 5 GB and I would like to know how to improve it

**Comment by jdalsem** [comment]
dear @AbdulazizSobh without more information about the reason you db is large, the specifications of your database, your environment architecture and your expected response times we can not give you any advice here. We have multiple users with very large database that work perfectly fine (but they also increased server specs accordingly).

Use a search engine to find tips on how to analyse/tune your database.

If, after analysis, you think we can improve Elgg, you are free to give us some tips. For now i am going to close this ticket.
