### ISSUE TITLE
How to show the description of the topic in the preview?

### ISSUE THREAD

**Issue by AbdulazizSobh** [Elgg/Elgg#13414]
When I post a topic, personal file, or anything on the site, the topic description appears the main description of the topic, not the topic description.
Also, I noticed that in previous releases, the abstract could be displayed normally

**Comment by jdalsem** [comment]
Your description is a bit unclear... could you explain with a screenshot?

**Comment by AbdulazizSobh** [comment]
Simply, when a site’s topics appear in search engines, or even when sharing on Facebook or sites that allow a preview of the links, the topic description appears. The main description of the site, not the topic description.
All I want is the emergence of the description of the topic, which previously was done automatically by taking or a paragraph from the topic
[](https://i.imgur.com/oiqXFnA.jpg)

**Comment by jdalsem** [comment]
As far as i know Elgg always has put the site description in the meta information of a page. There are SEO plugins that enrich this kind of data, but i do not think Elgg has changed this. There might also be a change on 'the other side' that scrapes information from a page that has changed. Maybe now it is using the description instead of the page content... this might also be because of inaccessability of the content, for example with walled garden sites.

Have a look at the source code of your pages... if the description meta element in the head part of the html contains the description of the site, that is the reason the scrapers show that information. Check with older versions of Elgg and/or your site to confirm this meta information has changed.

You can see here that Elgg puts the site description in the description metadata https://github.com/Elgg/Elgg/blob/3.3/engine/lib/views.php#L443

This was also the case in Elgg 2.3
https://github.com/Elgg/Elgg/blob/2.3/engine/lib/views.php#L558

Please update us when you have investigated this further

**Comment by AbdulazizSobh** [comment]
Which file should I check

**Comment by jdalsem** [comment]
Dear @AbdulazizSobh, Elgg fills the description meta in ``engine/lib/views.php`` on line 443. But like i said earlier, Elgg is a modular system, so other plugins might interfere with this information.

**Comment by AbdulazizSobh** [comment]
I have tried to close all plugins and check if one component captures that but still the problem

**Comment by jdalsem** [comment]
that makes sense, as you described how it should work by default in Elgg... so there is no problem as far as i can tell. Your described behaviour is not what i expect from Elgg.

**Comment by AbdulazizSobh** [comment]
So where is the problem and how do I solve it?

**Comment by jdalsem** [comment]
You solve it by investigating it further. Based on the current information i see no issue in Elgg. Once you finished your investigation and still think the problem is in Elgg, you can report that here. Make sure to describe the steps to reproduce it on a 'clean' Elgg installation (with no non-elgg plugins enabled). I have given hints in previous comments on where to start your investigation.
