### ISSUE TITLE
[Feature request] Elgg 3: clearing cache when migration

### ISSUE THREAD

**Issue by gnh1201** [Elgg/Elgg#13426]
Recently, I encountered the following error while migrating Elgg to another server.

> The page you are trying to view does not exist or you do not have permissions to view it

This is resolved by clearing the cache. However, there is no such description in the error message. I think it would be good to include that description in the message.

**Comment by jdalsem** [comment]
you get the message because the system probably has views on new file locations (because you migrated). Part of the migration should always be flushing the cache. That will not part be of the message.

In the duplication/migration docs it is mentioned to flush the cache: http://learn.elgg.org/en/stable/admin/duplicate-installation.html#run-upgrade-php
