### ISSUE TITLE
Elgg 4.0.0-beta.3 : Comments cannot be seen under the Blog Activity item

### ISSUE THREAD

**Issue by daniyaree** [Elgg/Elgg#13640]
A series of comments usually always appear under Blog Activity item in the Activity or River page. 
However, if an user is logged in he cannot see this. The user/member has to logout to see this. Please see the screenshot.
This happens with Elgg 4.0.0-beta.3, default installation and php8x

![1elg](https://user-images.githubusercontent.com/43325988/129778800-4eb6bfd4-3225-4b44-afae-ef494d33dd62.png)

**Comment by jeabakker** [comment]
In #13179 we fixed issue #4925.

On the 'All' activity page we don't show comments on activity items because it caused to much duplication of information. On the 'Mine' / owner page of the river you get the comments below the river item (or on the 'All' page if you filter by an activity type eg 'All blogs')

**Comment by iionly** [comment]
@jeabakker But then the comments should also not show for logged out visitors. Could it be that with no tabs displayed the comments below entity entries are not omitted? But I must say I find it worse if the comments are displayed on some tabs (owner / mine) but not on others. IMO rather adds to the confusion instead if reducing it. Also, with some comments shown the motivation to also comment might be higher - especially on the ALL tab which is most likely the default. I wouldn't need this kind of motivation on the MINE tab to comment on my own stuff...

**Comment by daniyaree** [comment]
1.
So, each comment made to a blog post will add a river entry, ten or twenty successive comments added to a blog post will give a series of river entry and will show the same Blog post title twenty times and push other relevant river entries - push them further down and out of view - that is certainly not wanted and that is more hell of a duplication of that same Blog Post title. So how is being duplication killed? Ideally it should be latest x number of comments under a blog post, with "x more" link and comment/reply box and bump this whenever there is new comment. Instead of several entries about the same blog post.

But the above exercise is not needed that much as coder and coding time is scarce. Why kill what was in Elgg 2x and probably 3x and to what users or site members were already accustomed to ? 

2.
How do I reply directly to a blog post via a text comment/reply box from the All tab/Home page once I log in

3.
Why a difference appearance of what home url shows  after I log in - this is what iionly also says above. But please do not respond to this by killing the feature for non-logged in user, instead re-instate it as before for logged in users too - this is a humble request. 

4. ""On the 'Mine' / owner page of the river you get the comments below the river item (or on the 'All' page if you filter by an activity type eg 'All blogs')"""

How will the site member know this UI/UX? Please make this uniform across all pages and all tabs.  Thanks.

**Comment by jeabakker** [comment]
> But then the comments should also not show for logged out visitors

> Why a difference appearance of what home url shows after I log in - this is what iionly also says above. But please do not respond to this by killing the feature for non-logged in user, instead re-instate it as before for logged in users too - this is a humble request.

This happen only on the home page, this is a bug

> Also, with some comments shown the motivation to also comment might be higher - especially on the ALL tab which is most likely the default. I wouldn't need this kind of motivation on the MINE tab to comment on my own stuff...

Use case: 
- User A writes a blog
- Users B,C,D,E and F comment on that blog

On the All activity page we see activity for
- users F,E,D,C and B
- and the original blog activity from A (without comments)

Since the comments are already shown as activity no need to repeat it with the blog.

On the Owner page of User A
- an activity about the blog (with comments)

Since the owner didn't write the comments, we show the latest comments

On the Owner pages of users B,C,D,E and F
- an activity about the comment on blog of user A

> Why kill what was in Elgg 2x and probably 3x and to what users or site members were already accustomed to ?

I understand that change can be hard sometimes, but sometimes it needs to be done

> How do I reply directly to a blog post via a text comment/reply box from the All tab/Home page once I log in? Previously I could do this - post a quick comment from home page (all tab or whatever) to a Blog post - now I have to apply filter and then choose blogs and then a different page will load and then I see the comment box!!! Why this circumvention to what can be done directly or what was already there ever for a long time.

This should still be the same (clicking on the comment icon in the river activity), but this looks to be bugged at the moment

>> On the 'Mine' / owner page of the river you get the comments below the river item (or on the 'All' page if you filter by an activity type eg 'All blogs')
> 
> How will the site member know this UI/UX? Please make this uniform across all pages and all tabs. Thanks.

What information is the user missing? All the information is still there, just not duplicated.
