### ISSUE TITLE
[Bug]: New install MySQL version check does not validate MariaDB versions

### ISSUE THREAD

**Issue by pstier** [Elgg/Elgg#13879]
### Elgg version

4.1.0

### Source of your Elgg installation

Elgg.org website

### Describe the bug

Phil from the Installatron team here. We're trying to get version 4.1.0 deployed but are seeing issues on MariaDB. We receive this error:

> MySQL must be version 5.7 or above. Your server is using 5.5.5-10.5.13-MariaDB.

MariaDB has been supported before, so I suspect something changed regarding the version validation?

### Steps to reproduce

Try an install using a MariaDB database.

**Comment by RiverVanRain** [comment]
Just successfully installed Elgg 4.1 on 10.3.17-MariaDB:

- via Composer - no errors
- via Unzipping archive - no errors

**Comment by jeabakker** [comment]
> MariaDB has been supported before, so I suspect something changed regarding the version validation?

MariaDB has never been officially supported. But since MySQL and MariaDB are very similar it 'should' work. But we personally have encountered situations where there is a difference in SQL parsing.

And yes we recently made a change to the server validation. 

We're going to investigate how we're going to handle MariaDB

**Comment by pstier** [comment]
Thank you for the update!

Phil

**Comment by jdalsem** [comment]
We decided to not 'fix' the installer for Elgg 4.1.x. However we added a follow up ticket for v4.2 to investigate if we can officially support MariaDB (https://github.com/Elgg/Elgg/issues/13894)
