### ISSUE TITLE
[Feature]:  Why is it returned as a string?

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#14264]
### Describe the feature

https://github.com/Elgg/Elgg/blob/4.x/engine/classes/ElggUser.php#L488

We can return as mix: string|array. 
That's how it was in Elgg 3.

**Comment by jeabakker** [comment]
Since plugin (user) settings are stored in the private settings table it only could contain a single value (string) since the private settings table doesn't store type information (unlike the metadata table).

So we type hinted it to a string.

If you set an array value in the ``elgg-plugin`` that you always would have a problem between the static config value and the user configured value.

**Comment by jdalsem** [comment]
AFAICT the private settings in Elgg 3 would always return strings... why do you think (or how did you do it) that in Elgg 3 it could return an array from `elgg_get_plugin_user_setting()`?

**Comment by RiverVanRain** [comment]
Got it.
