### ISSUE TITLE
[Bug]: Profile's admin toggle menu not working

### ISSUE THREAD

**Issue by rohit1290** [Elgg/Elgg#14492]
### Elgg version

5.0.7

### Source of your Elgg installation

Composer install

### Describe the bug

When I click on the "Admin Option" menu to expand that, the toggle is not working.

![image](https://github.com/Elgg/Elgg/assets/2772844/3e75e710-7e35-4960-bcb7-3fddd83c49b1)

### PHP version

8.1.5

**Comment by jeabakker** [comment]
I'm unable to reproduce this issue on my Elgg 5.0 installation.
I've only enabled some core plugins and don't have an issue.

Are there any 3rd party plugin active on your site?
Are there any CSS or JS issues in the console?
Any messages in the error log?

The 'Admin Options' menu should be below the links to Activity, Blogs, etc and should be red. Since this is not the case in your screenshot, I'd like to know a bit more information.

![afbeelding](https://github.com/Elgg/Elgg/assets/881958/69ab1efd-5f77-4b7c-b16e-08b259501bc3)

**Comment by rohit1290** [comment]
It was indeed an issue with third party plugin. Closing the issue now.
