### ISSUE TITLE
[Bug]: Default site language settings don't work

### ISSUE THREAD

**Issue by RiverVanRain** [Elgg/Elgg#14617]
### Elgg version

5.1.5

### Source of your Elgg installation

Elgg.org website, Composer install

### Describe the bug

Discussion is [here](https://elgg.org/discussion/view/3308094/default-site-language)

### Steps to reproduce

1. Go to Site settings
2. Select the default site language, e.g. 'Spanish'
3. Browse the site or log out - all on 'English'

### PHP version

8.3

**Comment by jeabakker** [comment]
Probably your browser is in English so that takes president over the site language.

see https://elgg.org/discussion/reply/view/3308339/3308094

**Comment by iionly** [comment]
@jeabakker I think I posted this before and I still haven't changed my mind that relying on the browser language setting without giving the site admin clear guidance what to expect (and maybe even better: a site setting to set the site language both for logged in AND OPTIONALLY ALSO for logged out visitors) would help a lot. If a visitor comes with the browser language set to a language with a low translation rate there will be a bad first impression due to mixed language output and there's no way to prevent that if the site admin will give the logged-in members the choice to still select the language even due to lack of completeness.
