### ISSUE TITLE
Make external authorization methods integration easier

### ISSUE THREAD

**Issue by Srokap** [Elgg/Elgg#5714]
Right now we can easily write additional PAM and it works great. We could add specific plugin hook for password change to not require duplicating control of `password` and `password2` inputs and tapping to usersettings save.

**Comment by jeabakker** [comment]
Adding an external authorization source can currently already be done (also by plugins).
Changing the account form to have a different implementation of password change handling can also be done with a few hooks/view overrules

Since adding a different / additional authorization source (like `Authorization` header) there is no need to change anything in core
