### ISSUE TITLE
Require at least 1 active anti-spam plugin or disclaimer checkbox to open registration

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5872]
In addition to #5871, I think we should more directly warn site admins that open reg comes with the responsibility to fight spam.

Aside: I see new site owners dealing with this without initial guidance and it seems like a terrible first impression to give them. We should be able to direct them to the essential spam plugins, and maybe consider bringing them into core.

**Comment by iionly** [comment]
It's been a while since this discussion was started and still unresolved.

"Requirement" of an anti-spam plugin during installation seems too much (intranet sites won't need it, private sites with registration turned off won't need it). Adding functionality directly to core seems not a choice (especially if 3rd party service involved). An anti-spam plugin with a 3rd party service might not yet be usable during installation (api key required, admin has not yet registered for the service, or the admin wants to use an alternative plugin/service).

How about adding an anti-spam plugin (Spam Login Filter? Or other suggestions...) like it is done for example with the "Login As" plugin as composer requirement? It does not need to be active by default but it would help especially people new to Elgg to have it already included in a basic Elgg installation.

It could be a new "Feature" for Elgg 2.3 to have an anti-spam plugin bundled.

**Comment by iionly** [comment]
It's been a while since this discussion was started and still unresolved.

"Requirement" of an anti-spam plugin during installation seems too much (intranet sites won't need it, private sites with registration turned off won't need it). Adding functionality directly to core seems not a choice (especially if 3rd party service involved). An anti-spam plugin with a 3rd party service might not yet be usable during installation (api key required, admin has not yet registered for the service, or the admin wants to use an alternative plugin/service).

How about adding an anti-spam plugin (Spam Login Filter? Or other suggestions...) like it is done for example with the "Login As" plugin as composer requirement? It does not need to be active by default but it would help especially people new to Elgg to have it already included in a basic Elgg installation.

It could be a new "Feature" for Elgg 2.3 to have an anti-spam plugin bundled.

**Comment by jdalsem** [comment]
https://github.com/Elgg/Elgg/commit/57ac75ecfec978e8f46ffa6687d9dd78022e776b made registration disbled by default. If you need any spam plugin for your site is up to you. Elgg is currently not providing one, so there will be no requirement.
