### ISSUE TITLE
Make title/description metastring IDs in entities table

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#5888]
This is #2675, but storing the title/description in metastrings.

**Comment by jdalsem** [comment]
So the suggestion is, instead of moving title/name/description to the entities table, to move them to metadata? And drop them from the xxx_entity tables? What will be the benefit? 

If there is no need for the title/description, there is also no valid reason anymore to keep the xxx_entity tables alive. Just move all the stuff to metadata and get rid of those extra tables.

**Comment by mrclay** [comment]
Indeed the goal of this (and #2675) is to get rid of several of the xxx_entity tables, but adding 2 TEXT (and really we need to go to MEDIUMTEXT) columns to entities seems like it would have a negative impact.

It also just seems like if we're going to use metastrings, this is exactly what it's for.

**Comment by jdalsem** [comment]
This is a nice thing to tackle for 2.0

**Comment by jdalsem** [comment]
related to #5459 (dropping a column in the users_entity table)

**Comment by jdalsem** [comment]
closing this as the current path is to denormalize metastring in metadata table, so metastrings table will be removed... maybe title and description will be added to the entity table
