### ISSUE TITLE
feature: generic 'featured item' method for entities

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#6293]
some plugins, such as 'blog_tools' allow entities to be featured, so that views/widgets can be created which only display the featured items.
this allows admins to provide a focus to the site and to draw attention to the most useful info on the site.

i think a core function should be added to allow all entity types to be featured. widgets can then include the options to display only featured items or not.

**Comment by mrclay** [comment]
Another case for entity list #2567

**Comment by jdalsem** [comment]
Closing in favor of a lists api as concluded in #7888

**Comment by propertunist** [comment]
this was passed on to the 'entity list system' ticket and then rejected as not being part of that change. so i request to re-open this ticket, as advised here https://github.com/Elgg/Elgg/issues/2567

**Comment by hypeJunction** [comment]
I think this is a perfect candidate for a plugin, in core or otherwise. I do not think we will be adding another method to the entity classes. Just simple metadata setter/getters would work.

- add setitngs to specify which type/subtype pairs can be featured (or perhaps context based approach is better ```$entity->featured = 'groups';``` where featured is multi metadata)
- add menu items (ajaxify)
- add permission checks
- add menu item to page filters
- route featured pages
- create widgets

I don't see anyone on the core team or contributors working on this. I would imagine if you create your plugin, most of us will be happy to contribute. I have too much on my plate as is, and featured items are not high on my priority list.

**Comment by ewinslow** [comment]
If this is based on entity list API I think the only thing to do is standardize on the name of the list.

**Comment by ewinslow** [comment]
Would "featured" be equivalent to "sticky" in the case of discussion forums?

**Comment by propertunist** [comment]
@ewinslow - good question. personally, i would like to see the ability to switch between featured and non-featured items in a list using just a one-click ajax action.. which would act like a list filter. this is similar, though not exactly the same as a sticky; in that sticky's are intended to always be seen at the top of the list, whereas the featured items are more of an 'editors choice' type of selector. some users may be attracted to look at the list of featured items and others may not be so attracted to look at them, whereas sticky's are the admin 'sticking' their activity into the user's viewport whether the user likes it or not!
if the stickys and featured items are separated, then that also gives the possibility for having a list of featured topics on the homepage, for example, while not being forced to include 'forum guidelines' and other common 'sticky' topics within that featured list. flexibility is always helpful for admins.

**Comment by mrclay** [comment]
The lists API will handle these cases easily. https://github.com/mrclay/Elgg-elggx_lists_api#using-a-list-in-queries

**Comment by jdalsem** [comment]
Because of this discussion, i started #7888. With the lists api, there is only one question left, what will be the standardized name (if we would choose one). Every plugin can have its own featured interpretation, so if we use the lists api, there is no need to leave this ticket open as there is no action left related to this ticket. Core currently uses "featured" items on 1 location (groups plugin). It uses metadata for it `featured_group`.

**Comment by mrclay** [comment]
I figured a group might have one big /GUID/featured list, and for viewing you could filter that by subtype or whatever.

Plugins making their own list reduces the potential for collaboration, but nothing stopping them: /GUID/myplugin:featured.

**Comment by mrclay** [comment]
In a site I run users can create "collection" ElggObjects, or add attachments to any other their content, including comments. All list powered. When you view any entity on the site, you can lookup which collection(s)/attachments it's in.

**Comment by jdalsem** [comment]
So we only need to write a best practice on how to use lists. If we add that action to the API lists ticket, do we still need this ticket?

**Comment by mrclay** [comment]
I guess the question is whether core is going to provide the front-end UI for this feature in a new bundled plugin. I would vote no.

**Comment by mrclay** [comment]
We can always re-open if we decide to pull in a 3rd party implementation.

**Comment by jdalsem** [comment]
Also a no for me, as the problem will be to get a consensus on what "featured" means

**Comment by ewinslow** [comment]
FWIW, I'd also vote no on providing a UI.

@propertunist do you feel this issue is resolved sufficiently?

**Comment by propertunist** [comment]
@ewinslow - from what i gathered here, the decision was made not to code this, i'm not really clear how this has been resolved, did i miss something?

**Comment by mrclay** [comment]
Today, core is not interested in developing a plugin that does this. We are first focusing on underlying APIs that will make it easy and fast. Later we may concider reopening this.

**Comment by propertunist** [comment]
i see, ok.
