### ISSUE TITLE
More uniformity in form elements markup

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#6356]
Perhaps, we should start moving towards a more uniform markup of form fields, so that they are consistent across the core and third-party plugins. Currently there is not much convention, so we end up with forms that are very hard to style.

I believe we could use a wrapper view, which would use the following:
- label text
- input view
- help text
- validation result placeholder/text

Research:
- http://www.uxmatters.com/mt/archives/2006/07/label-placement-in-forms.php

**Comment by hellekin** [comment]
Sorry for the delay.  No @ewinslow, removing the class doesn't change anything besides the addressing path to the element (instead of to the class).

Dissociating error messages from the label allows more control over how the message shows.  With absolute positioning you can still "tie" the message to the label, but if you prefer having error messages independent from the label (e.g. on a line by themselves or on the top bar), you can as well much more easily (if at all).

**Comment by hypeJunction** [comment]
I have been doing a lot of work with forms and validation lately. I am packaging everything up into a bunch of smaller plugins. First one is here that standardizes the markup: https://github.com/hypeJunction/elgg_forms.

Main motivation is have a view for everything so it's easy to extend and replace. There were some themes that needed the markup to into 3 columns, so it was a hassle with large views.

**Comment by mrclay** [comment]
@hypeJunction looks awesome. :+1: for adding the views and elgg_view_input() to core pretty much as is.

**Comment by hypeJunction** [comment]
Ok, I will wrap it up into a PR soon.

**Comment by hypeJunction** [comment]
PR: https://github.com/Elgg/Elgg/pull/9086
