### ISSUE TITLE
Pass ckeditor config array through a hook

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7131]
Would be nice to alter bits of this without replacing the whole view.

**Comment by mrclay** [comment]
Seems to be blocked by #7926.

**Comment by jdalsem** [comment]
We could also close this because it is easy to override the config view

**Comment by hypeJunction** [comment]
@jdalsem I think just overriding a view is not the ideal solution, since there may be several plugins trying to alter the config.

**Comment by jdalsem** [comment]
agree, that is why i made #7896, however that was not accepted because of race condition in AMD modules. Alternatively we could change the view to merge `$vars['ckeditor_config']` with local defaults. That way you can influence the config from multiple plugins by hooking on the view and change the vars...

**Comment by mrclay** [comment]
@hypeJunction Maybe give #7926 a look.

**Comment by hypeJunction** [comment]
Hm, ckeditor is already extremely slow, having it wait for everything else to load seems like a major performance blow.
Perhaps ckeditor/init should wait for $(document).ready(); and in the meantime elgg.config.ckeditor could be manipulated by plugins?

**Comment by hypeJunction** [comment]
I guess I am contradicting myself :)

**Comment by mrclay** [comment]
I have a solution for this, but can't quite get it working: #8080

**Comment by mrclay** [comment]
Working solution here #8085
