### ISSUE TITLE
The public_pages, walled_garden hook doesn't pass the default list to the hook

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#7235]
It's odd that it doesn't. If there's a reason for this, it should be documented in code.

**Comment by jdalsem** [comment]
i think the reason for this is that if you allow plugins to override the defaults, they could potentially lock themselves out of a walled garden site without the ability to use the site. The defaults are the minimal requirements instead of default behaviour. Do we need this documented in the docs? Or should we add a comment to the code?

**Comment by jdalsem** [comment]
Is there a use case where you wish you could have changed the defaults?

**Comment by jdalsem** [comment]
Anybody else with an opinion on this? @Elgg/owners

**Comment by jdalsem** [comment]
bumping this for feedback

**Comment by beck24** [comment]
I think it should be passed, even with the possibility of plugins doing something dumb - that's on developers, you can be dumb pretty much anywhere.  I'd rather have the info available and not need it than be stuck without it if I do need it.  In case a dev does lock themselves out while developing they can simply disable the plugin or fix their code.  It's easy to pass it though, so I say lets do it.

**Comment by jdalsem** [comment]
the problem is not passing it along, but more in not doing the merge with defaults anymore (`array_merge($defaults, $plugins)`)

**Comment by jdalsem** [comment]
Fixed by #9883
