### ISSUE TITLE
Language code names should be hard-coded to target language

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#7236]
Currently the language setting has (most) options in English:
- English
- Finnish
- Japanese

Wouldn't it be better not to translate them at all but to have them hard-coded to the target language:
- English
- Suomi
- 日本語

I realized this when working on a project where the target audience includes 6-year-old children. Most of them have no idea that "Finnish" means "Suomi".

**Comment by jdalsem** [comment]
retrieving installed translations, for example for the user setting to change the language, will always try to translate the language code in the language of the code, so for example if you switch to 'Dutch/Nederlands' from 'English' you will see 'Nederlands' (the local language) as an option.

So this is currently working as requested, the problem is, that the Finnish translation file currently has 'Finnish' as the translation for the language code. This could be changed to 'Suomi' in the translation to solve the question.
