### ISSUE TITLE
Add widget button on profile and dashboard jumps when clicked

### ISSUE THREAD

**Issue by PerJensen** [Elgg/Elgg#7705]

**Comment by jdalsem** [comment]
could be... i thought i had that fixed but will look into it for you

**Comment by jdalsem** [comment]
the small jump is related to the `.toggle()` jquery function that toggles hidden elements by setting `display` to `inline` instead of `inline-block`. Can't seem to find a way around this... anyone with an idea?

Only thing i can come up with is not toggleing with toggle but use `.toggleClass("hidden")`

**Comment by PerJensen** [comment]
I can't find an easy solution either. How about the way add/remove friend does it?

**Comment by ewinslow** [comment]
All HTML elements have a "hidden" property that's meant for this. Set it to
true to hide and false to show. No need to set display or classes or
anything like that.

**Comment by jdalsem** [comment]
@ewinslow not quite true at the moment. Elgg has a `rel=toggle` functionality that does a jquery `.toggle()`. The buttons on the widget panel use that functionality. However the issue is that hidden elements that are toggled by jquery get `display:block` but these buttons here need `inline-block`. Jquery is not detecting correctly which display type it needs to set for elements that are hidden by default. The guess it makes is wrong and as far as i now we can't influence that.

**Comment by ewinslow** [comment]
We can fix by implementing our own toggle code that uses the hidden property then, right?

**Comment by jdalsem** [comment]
Yes we can, but only for `.toggle` but not for `.toggleSlide()`. That will result in some mixed code in the `rel=toggle` functionality, but it will do the trick.
