### ISSUE TITLE
Report this page link missing from pages without sidebars

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7729]

**Comment by iionly** [comment]
There's a "Report user" option on profile pages though.

**Comment by jdalsem** [comment]
@mrclay do you really want this fixed? This problem is not limited to profile page only. Currently the 'report this page' is positioned in the 'extras' menu which by default is located in the sidebar. So on every page that does not have a sidebar the action to report the page is missing. Maybe moving the action to the footer menu makes more sense. That will make sure you have the link always available.

**Comment by mrclay** [comment]
Footer menu sounds better. 3.0 would be fine with me.

**Comment by hypeJunction** [comment]
I am in favour of loosing extras menu (I get rid of it in 100% of my projects). It doesn't make sense, list type toggle is totally out of place, rss if someone cares enough they will find it in  the footer, bookmark can go in topbar (anyone even uses it - seems counter productive bookmarking links from the same site on the site). That was my 5 cents.

**Comment by jdalsem** [comment]
i agree we could loose the extras menu completely. I will put this on the 3.0 milestone
