### ISSUE TITLE
You can never receive notifications from yourself

### ISSUE THREAD

**Issue by brettp** [Elgg/Elgg#7754]
https://github.com/Elgg/Elgg/blob/1.9/engine/classes/Elgg/Notifications/NotificationsService.php#L252

This seems like an arbitrary decision that causes confusion when notifications don't appear. Use case is our users are accustomed to listserv, and like to have an email "confirmation" for their actions. There's not a graceful way to do this without modifying core.

**Comment by juho-jaakkola** [comment]
How about calling ```notify_user()``` in the ```[prepare, notification:action:type:subtype]``` hook? It's called only once per notification and includes everything: subject, summary and body.

**Comment by brettp** [comment]
Doesn't notify_user() go through the same system?

**Comment by juho-jaakkola** [comment]
No wait. Now I mixed up things. My suggestion was *supposed* to be the ```[get, subscriptions}``` hook. *That* is called only once per notification.

But it doesn't get the text content so you'd have to generate the message yourself.

**Comment by juho-jaakkola** [comment]
No, I don't think ```notify_user()``` checks whether recipient is the actor.

**Comment by brettp** [comment]
I meant I thought `notify_user()` used Elgg_Notifications_NotificationsService::sendNotifications(), but it looks like it doesn't, which is good in this case.

`[get, subscriptions]` looks like it should work. I'll give it a try and then report back.

**Comment by Facyla** [comment]
+1 on allowing to send a notification to User who performed this action. It is not very common but should be overrided in a clean way.
The hook get,subscriptions works fine, but function sendNotification breaks it by hard-coding remove the actor of the content, which forces to use weird workarounds to send the email to that only user.

In my use case, i want to be able to send an email even to the actor, because the sent notification contains a "reply by email" link (which allows to reply to a specific email to publish on the Elgg site).
