### ISSUE TITLE
Elgg 1.9.8 release misses a lot of content of the vendor directory

### ISSUE THREAD

**Issue by iionly** [Elgg/Elgg#7780]
I don't know if this was in any way intentional or an error in the built process.

**Comment by mrclay** [comment]
Probably an error! I did not try an install of it. I can't look into this for several hours. cc @Elgg/owners

**Comment by Srokap** [comment]
We do not ship dev dependencies anymore: https://github.com/Elgg/elgg-scripts/blob/master/build/build.sh#L236,

So it LGTM on first glance: https://github.com/Elgg/Elgg/blob/1.9/composer.json

It's better visible in case of 1.10 release

**Comment by iionly** [comment]
I thought the dev dependencies were only meant to be omitted in case of checking out the repo from github but still to be included in the downloadable packages of the Elgg releases at the community site.

**Comment by Srokap** [comment]
Motivation is that dev dependencies are not necessary to just download and run Elgg, so they're obsolete from the distributed packages. In case you do need to run ie. phpunit tests, you need shell access anyway, so that should be no problem to run `composer install` to get additional stuff.

See for the case of 1.10. We include:
- "mrclay/minify": "~2.0",
- "knplabs/gaufrette": "~0.1.0",
- "tedivm/stash": "~0.12",
- "ircmaxell/password-compat": "~1.0",
- "roave/security-advisories

But don't:
- "phpunit/phpunit": "~4.1",
- "elgg/sniffs": "dev-master",
- "squizlabs/php_codesniffer": "~1.5",
- "simpletest/simpletest": "~1.1"

I think we'll be growing our dev dependencies over time pretty significantly, that including node_modules, and I don't intend commit all of this junk into repository especially as in case of npm we deal with different architecture compatibiliies. Mostly thinking about whole environment for JS integration testing.

We could write a blog post about that for sure.

**Comment by iionly** [comment]
Unfortunately, "composer install" doesn't work for me anymore, neither for the Elgg 1.9.7 (not tested yet for 1.9.8 but I don't think it would make a difference) nor Elgg 1.10.0 release. Using the zip archive of 1.10.0 or cloning 1.10 from github made no difference either.

The thing that fails to work (on any Elgg version) is the code_review plugin from @Srokap. The error is "Class CodeStyle does not exist". I guess it's not loaded due to some issue with the class autoloader that would have to get configured with "composer install", right?

With "composer install" the error message is:
[RuntimeException]                                                                                                                     
The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages.  

A "composer --no-dev install" works but does no make the code_review plugin to work.

If I try it with "composer update" I run into memory issues:
Loading composer repositories with package Information
Updating dependencies (including require-dev)                                                     
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/Rule.php on line 62

If it's not an Elgg issue it might be due to upgrading to php 5.6 recently. I know for sure that "composer install" worked in the past but it does not anymore with the recent releases of Elgg 1.9 and 1.10

**Comment by iionly** [comment]
It seems the issue could be resolved by doing a "composer selfupdate" first. KInd of annoying that the error message gives no indication what might be necessary to do to fix the issue but that's a problem of composer.
