### ISSUE TITLE
Extract widgets to a plugin

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#7791]
I know a lot of people find value in these, but I think they make more sense as a plugin of Elgg than a core concept. 

I feel they lead to less thoughtful design of sites because the burden of design is pushed to the end users, which makes no sense to me. Users don't want to design sites, they want to get some value out of them. It should be up to the admin or developers to do the design. That level of customization is just busy work and not a significant value-add.

In fact, I think widget-based layouts can actually be harmful to sites, since profiles are not laid out in any reliable fashion. Anyone browsing profiles has to relearn the layout for every new profile you look at. It makes apples-to-apples comparisons of users harder, and it makes finding information harder, since the information might be in a different place or not visible at all depending how the user has configured (or more likely, not configured) their space.

However, lots of sites use widgets and ColdTrick has a solid plugin in "widget_manager", which I believe allows admins to specify widgets and lock them in place to get some kind of consistency out of widget layouts, so it's not like we can just drop them entirely, even for 2.0.

It also probably won't be a trivial effort to remove widgets from core and we'll have to figure out what to replace them with -- the admin area depends on them on the dashboard currently, and the profile plugin depends on them heavily as well. There's also what to do about the question of core plugins exposing widgets for their content. Do we keep having them register widgets and just recommend the widget plugin be installed in order to access the widgets, or do we do that and _require_ the widget plugin to be installed? I'm leaning towards the former.

I'd be ok with moving the code for these things into a new repo like `Elgg/widgets` and just including it in the composer requirements for the sake of BC. ColdTrick guys could then beef it up with enhancements from widget manager.

@jdalsem @jeabakker thoughts?

**Comment by iionly** [comment]
I have to say I disagree. I think the widgets are a strength of Elgg. They provide an easy way of adding content "blocks" both for developers, admins and users.

I also don't think that the burden of design is pushed to the end-end user in a bad way:

* first of all the widgets layout is mainly used for "personal" pages (profile, dashboard) where a bit of customization might even be expected,
* the admin can define default layouts to lighten the "burden" of setting up the layout of profile pages and dashboards,
* the Widget Manager plugin provides options for admins to fix the layout and prevent adding and removal of widgets, if a consistent design is what the admins wants for his site.

The questions is: what kind of design do you have in mind as replacement for a widget layout? And would it be necessary to replace the design in Elgg core or wouldn't it be better to offer this alternative design option via a plugin? The only alternative design that comes to my mind is a FB-like timeline layout. But I honestly think this would be a step backwards because it puts everything on one large unsorted pile. A timeline is good to see the most recent activities but it is a bad approach to present the different types of content specifically. Also, the activity page / activity widget already offer a timeline (site-wide and user-specific). Additionally, the is the Timeline plugin that already offers such an alternative profile page design.

Instead of giving up the widget design I would rather add a few additional features to it in Elgg core (even if some of them are already available via Widget Manager and some of them also in the AU Sets plugin):

* switching to widgets also for group profile pages,
* allowing switching between 1-, 2- and 3-column base layout (both as side-wide setting / default layout and also as user-specific setting),
* allowing widgets itself to be 1, 2 or 3 columns wide,
* maybe for the sake of consistent design add an option to fix the layout to the site's default layout (in this case remove the edit buttons for users and also set the default layout for existing users, too).

**Comment by mrclay** [comment]
Difficult questions. A big problem is that Elgg as a team needs to be willing to make bolder (non BC) steps to improve the out of the box UX throwing away what really hasn't worked. We have to agree that some major release will be a New Thing (not 1.8 with makeup), shift our focus as devs to UX/UI, and welcome more talented designers from the community to help.

**Comment by mrclay** [comment]
There's no reason it must be non BC. We can just fork existing plugins and change which are activated by default. Want new user profile? Disable "profiles" and enable "profiles2".

**Comment by mrclay** [comment]
Sorry these ramblings are off topic. I'll move them.

**Comment by ewinslow** [comment]
> what kind of design do you have in mind as replacement for a widget layout?

This is a good question. I think an activity stream as a stock profile would be a fine option. The widgets profile layout could be a plugin.

I'm also thinking more mobile. 3 columns layouts just don't make sense any more IMO. We should be thinking default 1 column.

I'm definitely not a huge fan of adding any more features to core. I think we should modularize as much as possible. If there is any subset of features that could be extracted to it's own project, we should seriously consider doing that. It adds focus and clarity.

Also, since widgets are a ui thing, they are inherently unstable. Ui implementations and best practices and frameworks are changing all the time. I think it's definitely in our best interest to decouple ui stuff from core when possible.

**Comment by iionly** [comment]
> I think an activity stream as a stock profile would be a fine option. The widgets profile layout could be a plugin.

I guess we have different preferences here. :-) I don't like activity steam profile pages at all. But I guess it might not make a difference what the default is and if it's provided as plugin or directly in core as long as the widget layout isn't dropped completely but at least kept as a bundled plugin. "Bundled" seems important to me - to keep in mind that compatibility isn't lost due to future developments. The widget layout is one really good feature of Elgg and it would make me sad to see this feature getting dropped. Two different layouts to be offered seems a possibility (like "default" theme and "Aalborg" theme/plugin).

> I'm also thinking more mobile. 3 columns layouts just don't make sense any more IMO. We should be thinking default 1 column.

Have you checked out profile pages on Elgg 1.9 / 1.10 with Aalborg theme enabled recently? The column layout IS already adjusted depending on screen width, i.e. 1 column layout on mobile phones.

**Comment by jdalsem** [comment]
Closing this for now. Widget layouts and widget object will stay part of core. Plugins can decide if they want to use the layouts or not.
