### ISSUE TITLE
Replace elgg_get_config("group_tool_options") with hook

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7829]
https://github.com/Elgg/Elgg/blob/1.10/mod/groups/views/default/groups/edit/tools.php#L11

Currently you can register group tool options, but it is hard to conditionally add or remove an option. Maybe we could replace this with a hook mechanisme. We should maybe also look into a mechanisme to get the value form a group (currently it is metadata).

**Comment by jdalsem** [comment]
The groups plugin should just register a hook to return `elgg_get_config("group_tool_options")`. Plugin authors can then extend this conditionally.

**Comment by twentyfiveautumn** [comment]
I beat my head against the wall with this for a couple of hours the other day because I wanted the modules to appear in alphabetical order. Finally the lightbulb came on and I went to 
**/admin/plugins/**
and arranged the plugins in the order I wanted putting the groups plugin first. Not perfect but...

**Comment by mrclay** [comment]
If the config value was injected via $vars, you could use the view_vars hook to do this.

**Comment by jdalsem** [comment]
Feature is further discussed here: https://github.com/Elgg/Elgg/issues/9497
