### ISSUE TITLE
Replace site notifications with Juho's notifier

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7889]
Either completely replace the plugin, or somehow migrate all the features from [notifier](https://github.com/juho-jaakkola/elgg-notifier) into site notifications.

cc @juho-jaakkola 

List of needs that core doesn't currently support (by Juho):
- [x] Monitoring when user "reads" the notification: https://github.com/juho-jaakkola/elgg-notifier/blob/master/views/default/notifier/view_listener.php
- [x] Running relationships and annotations through the notifications system https://github.com/juho-jaakkola/elgg-notifier/blob/master/start.php#L37 
- [x] Combining multiple subjects https://github.com/juho-jaakkola/elgg-notifier/blob/master/views/default/notifier/messages/create/annotation/likes.php

**Comment by juho-jaakkola** [comment]
Added some TODOs to the description

**Comment by mrclay** [comment]
Are the TODOs strictly necessary to replace site_notifications with notifier? How much data migration is needed to switch?

**Comment by juho-jaakkola** [comment]
I guess I listed those TODOs simply because current approaches are a bit hacky to be accepted into a bundled plugin. I don't think there are any actual blockers.

I'm quite sure migration is not possible. Site notifications saves translated strings and notifier saves raw translation keys. It's not possible to map those together as plugins may have saved anything in site_notifications. And translation may also have changed after a site_notification has been saved.

**Comment by jdalsem** [comment]
Notifications in core have had various improvements the last few years. It will not be possible to take in the notifier plugin, but if there are specific improvements in the plugin that should make it to core, we are open for Pull Requests.
