### ISSUE TITLE
 creation of new theme for 2.0

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#7971]
as concluded here https://github.com/Elgg/Elgg/issues/7328#issuecomment-74762904

The theme should be in a seperate repo, but when ready it should be added to the elgg repo via composer

**Comment by ewinslow** [comment]
@jdalsem you have assigned this to yourself. Does that mean coldtrick is taking on the design?

**Comment by jdalsem** [comment]
no, but we now a party that will do that... i will ask them to start working on it

**Comment by ewinslow** [comment]
No rush, just curious!

**Comment by hypeJunction** [comment]
Could we first identify what we want from a new theme? Is there something
that needs changing/new features? Or we just talking color theme?
In any case do we want more theme maintenance overhead? Can it just exist
as a vendor theme?
I believe new theme would be justified if it were a collective baby where
everyone chimes in for a better UX-future.
I am just asking in case our goals for the theme could just branch aalborg
into 2.0 standard.

**Comment by ewinslow** [comment]
@hypeJunction good points

**Comment by jdalsem** [comment]
> Could we first identify what we want from a new theme? Is there something that needs changing/new features? Or we just talking color theme?

a brand new theme was the idea


> In any case do we want more theme maintenance overhead? Can it just exist as a vendor theme?

The party that will provide the theme will also commit to supporting it. I think the limited extra overhead will be needed to attract different users of Elgg. But it doesn't have to be in Elgg core, but we can pull it in with composer.


> I believe new theme would be justified if it were a collective baby where everyone chimes in for a better UX-future.

This could be a long debate, but as it is an opensource product, everybody already can chime in.




> I am just asking in case our goals for the theme could just branch aalborg into 2.0 standard.

This was already discussed in #7328 where the conclusion was to keep aalborg a seperate plugin, besides the core theme. But aalborg set a good standard, so we do not want anything that sets us back.

**Comment by ewinslow** [comment]
> a brand new theme was the idea

This doesn't help clarify anything for me. Perhaps we should just wait to see an early mock/proposal.

Mobile-first please :)

**Comment by rhisss** [comment]
I hope the new theme just goes beyond mobile-first and "fresh new paint"
It will be great UX, UI and user-friendliness as well as fulfilling user expectancy if it actually integrates or have the potential to integrate the various Elgg components and inputs thereof. Mainly Images, Link with thumbnail preview, Events and Location. A lot happens through, in and around the status/wire/textarea input box atop the Activity and Profile page these days. And Elgg seems dated and not-in-sync with modern times.

This is not about copying something else, or "see they have done it, lets also do it" but it is about user-ease and generating user-addiction so that they post content for the site. Elgg is not just for Devs who can then build whatever for their clients but also for users like us who can straightway use it to have a site that works great, and thus we can concentrate more time on user and content-generation.

Now to have an understanding of what I am saying, please have a look at these demos and how they integrate various stuffs in one place ( remember the old facebook theme for Elgg?) - this form and menus and sub-menus are superbly responsive also. I am giving links to 2 demo sites but almost all social scripts have developed this or developing this

http://demo.jomsocial.com/index.php
http://easysocial.stackideas.com/profile

![1](https://cloud.githubusercontent.com/assets/3778500/6834923/27948d5e-d35d-11e4-8919-b52262a18abf.PNG)
and
![2](https://cloud.githubusercontent.com/assets/3778500/6834933/3baec354-d35d-11e4-8ae5-5c78131bd7ae.PNG)
Please have a look.

**Comment by jdalsem** [comment]
The theme will not provide features, so the "fancy status updates" will not be part of this.

Adding features to status updates is however a good idea, but it should be party of the activity/status functionality, so it can be used in any theme and not only this one.

**Comment by rhisss** [comment]
Thanks jdalsen. IMHO, this is not "fancy". It is what users are getting accustomed to and expects in 2015 :)
It is also not "features" - the features are already there in core or some major supported Elgg plugin. The theme needs to "inteliigently" pick up those ( see old facebook theme for Elgg 1.7 or 1.8) .
If it does not it will be yet another theme ( with responsive layout and new coat of paint).
Anything can be used for any theme but if Elgg 2 ports with such theme it can be the basic gold standard so that the future other themes can be extended still beyond.
Thanks.

**Comment by twentyfiveautumn** [comment]
@rhisss you should release it as a plugin on https://community.elgg.org/
so we can all get a better idea of what you have there.
Thanks

**Comment by ewinslow** [comment]
@jdalsem what's the status of this? 2.0 is fast approaching.

Going to move this off the 2.0 milestone. Won't block the release.

**Comment by jdalsem** [comment]
Unfortunately this will not going to happen any time soon.
