### ISSUE TITLE
Improve error messaging on installation

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8024]
If someone installs Elgg 1.10 from the zip archive on a PHP 5.3 system, they get a white screen without a meaningful error.

Personally I think we ought to deprecate the zip archives for 2.0... composer all the way.

Do we want to do anything to improve this in the mean time?

**Comment by jdalsem** [comment]
I think you will have lots of issues with "simple" users that don't want it any more complex than download/extract/upload. The WSOD is related to the 5.4 requirement. They should read the manual to prevent that.

Is there no php check in the installer?

**Comment by ewinslow** [comment]
The installer breaks before it can perform the check.

In general, I don't like "read the manual" as a suggestion if we can avoid it, especially with the initial experience. It's on us to make the onboarding as smooth as possible. To me, composer feels the smoothest, but I have to keep reminding myself that command-line is super scary to some people...

**Comment by jdalsem** [comment]
> The installer breaks before it can perform the check.

maybe we should split it up in an extra step that can do the check

**Comment by mrclay** [comment]
Just up the version_check arg in install.php, rest of code in that file should even parse in 5.0

**Comment by iionly** [comment]
Please keep the zips. First, the installation via composer is not really any easier (espcially since you first have composer itself installed and useable). Secondly, there might be a certain number of users who have intranet Elgg sites without a connection to the outside world and they would need a stand-alone install archive in any case.

Maybe the info about php 5.4 and all other requirements could be added to README.txt or INSTALL.txt again. Right now this info is only available on learn.org. Even it's likely that not everyone would read the info in these files at least it's a good service to have this important info included without the need to visit a website.

**Comment by ewinslow** [comment]
"there might be a certain number of users who have intranet Elgg sites without a connection to the outside world and they would need a stand-alone install archive in any case."

This is a good point.

Also agreed that we should be more up front about our minimum requirements.

**Comment by jdalsem** [comment]
Closing this as we are very clear in our installation requirements and when releasing updates these changes in requirents are explicitely communicated.
