### ISSUE TITLE
Brand new install 1.10.3 - multiple js errors due to deprecated elgg.provide and bundled modules not upgraded

### ISSUE THREAD

**Issue by AnOldMan** [Elgg/Elgg#8093]
Brand new install 1.10.3 - multiple js errors due to deprecated elgg.provide and bundled modules not upgraded.

What version of your project is actually stable for test/install?

TypeError: elgg.get_language is not a function
default/js/elgg
var languagesUrl = elgg.config.wwwroot + 'ajax/view/js/languages?language=' + elgg.get_language();

TypeError: elgg.provide is not a function
default/js/lightbox
elgg.provide('elgg.ui.lightbox');

TypeError: elgg.provide is not a function
default/js/admin
elgg.provide('elgg.admin');

/admin/appearance/expages
	403 Forbidden
	/cache/1426919720/default/js/elgg.js

**Comment by brettp** [comment]
I just installed a fresh 1.10.3 and it's working without these issues. elgg.provide is not deprecated in 1.10, though require is the preferred method.

It sounds like your rewrite rules or data directory are not correctly configured. Please use the [community site](https://community.elgg.org) for support with this. If you open /cache/1426919720/default/js/elgg.js in your browser it will output why the request was forbidden, which might shed some light on what's going on. 

If it is a bug in core and not due to server config, feel free to reopen with more info.
