### ISSUE TITLE
Translations for entity attributes and metadata

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8096]
On a multilingual website, one would want to allow translations of entity metadata and attributes. Using language keys is not always an option, as that prevents from metadata being searchable in the target language.
In my current implementation of this need, I am overwriting getMetadata() method to check for language suffix on a metadata name, and it's quite hacky. It would be lovely to have some out of the box support for this.
One way this would be possible is by adding 'language' column to the metadata table.

**Comment by ewinslow** [comment]
This was a Google Summer of Code project a few years ago. Unfortunately it didn't go anywhere. We never got to a clear design or consensus.

I think we wanted to avoid changing the database schema though.

Another possible design is a "translation" subtype contained by the translated entity. It would just have all the translatable properties of the container on it, as well as the language.

But beyond this you would need to expose ui for translators, a ui for consumers, etc.

This would be handy on the Elgg community site, though. Lots of multi lingual activity going on, and I'd love to see more.

**Comment by ewinslow** [comment]
Actually the real problem with the SoC project was we never got any code so we had to cancel that project.

**Comment by ewinslow** [comment]
Also: How to manage/distinguish "user-submitted" translations vs "official" translations?

How do deal with edits to the original content? Needs to be a translation of a particular revision of the entity, but also: only revisions of translatable properties matter.

So all-in-all I really like the idea and think it could be awesome but there is a lot of work to do!

**Comment by hypeJunction** [comment]
I will see any useful code comes out of what I am working on now.

**Comment by ewinslow** [comment]
Might be good to be able to integrate with a 3rd party translation UI like transifex, rather than implementing our own translation UI.

Would love to see what you end up with. Honestly, I expect this to end up in a plugin, ultimately.

**Comment by beck24** [comment]
Drupal has content translations and it's done exactly as you mentioned - the node (equivalent of ElggEntity) is added to a translation queue.  Users with a translator role can pick nodes from the queue to translate into their languages.  The translation is simply a case of filling out the same form with the original values displayed along side each field.  The action of the form creates a new node, which is tagged with a language code, and a pointer is generated between it and the original (in Drupal it's a specific db column, I could imagine Elgg it would be a relationship).  When the node is edited/updated, the translations of it re-enter the queue to be reviewed.
When the node is requested for display, the viewers language is part of the query and returns the appropriately translated node if available.
I could see this being absolutely doable in a plugin if someone needed it.  It's certainly more of a CMS feature than a social one though.

**Comment by ewinslow** [comment]
I see it being very valuable for us. Translating our blogs, events, etc.
For a global audience... Very helpful.

**Comment by Facyla** [comment]
I'm thinking about this too these times :)

It would be very useful -besides objects- for translated user profiles...

I think translations could be a great feature ; i think it is not only an "editor's content which has to be translated", and also a possibility offered to members to add an "alternate language content", for a post, a comment, a group, or one's profile - and even on any displayable metadata, depending eg. on user languages preferences. 

Just a thought : if it is implemented as relationship, it would be valuable to have a "lang" meta on the original entity itself, because not all sites have a "default" language (can be auto-detected).

**Comment by Facyla** [comment]
We would need to have some new methods on ElggEntity, such as  ->getTranslation($lang_code) and the corresponding setter (which would duplicate the entity, add some meta -language- and define the relation to the original entity).

And that would also require some cascading cleanup when the "parent" entity is deleted, or some inheritance from the "original" entity - such as access rights.

In fact, the model should be defined so that a possible bad side-effect could not happen, which would be ending up with different URLs for the same content, provided in different languages. Maybe a more interesting example would be what happens when using Elgg's webservices, when retrieving a list of content : processing the same list, but getting it in an other language should not imply retrieving a new list of entities.

This functionnality should also consider SEO criteria, eg. have some html meta added to indicate that the content has alternate languages versions.

**Comment by ewinslow** [comment]
Agreed that a language or locale tag on the original entity would be great for specifying the language of that entity's content...

Could just be done with metadata though. Do we need to explicitly support it in the core entity attributes?

**Comment by Facyla** [comment]
Well, i gave it a quick try meanwhile :)  https://github.com/Facyla/esope/tree/master/mod/multilingual   (note this is a very quick piece of testing code, not an actual plugin).

I agree that a plugin can fully handle that, and add the needed metadata.
As i'm exploring, i think some routines would be made easier with core support, especially the routing from a "translation" to the "original content". 
I'm currently using the ->view metadata so the display of a translated entity is in fact re-routed to display the original entity + information on available translations, but this is a bit hacky. In that particular case, a hook on elgg_view_entity that would allow to check for some entity relationships (or metadata) before displaying would do the trick.

Do you have any output from the GSOC workshop ?   some discussed specs or expected features ?

I'll keep exploring this a little further... there are many other things to consider !

**Comment by Facyla** [comment]
Hi !

Latest version works for objects : 
- admin can define a set of "available locales" + a main one
- user who can edit a content can create a new version in another language (tied by a relationship to the original content + marked with a locale metadata)
- display uses only the "main" entity URL, plus a ?lang=XX code param in the URL
- a ->view property is set on the original and translated objects, and used as a late pseudo-hook to redirect to the proper URL, and display to right translation based on user preferences

While build on 1.8, it can actually be tested on 1.11 though it will require some changes later => https://github.com/Facyla/esope/tree/esope_1.11/mod/multilingual

I'd be happy to have your thoughts on this experiment ?

**Comment by ewinslow** [comment]
Cool. Will take a closer look later

**Comment by ewinslow** [comment]
Switching translations with "lang" seems reasonable. Is there a ui for end users though?

**Comment by Facyla** [comment]
Yes : 
1) regular readers can switch language using the flags in the entity menu (only the already translated content appear).
2) users who canEdit the content have all admin-set languages flags in entity menu : a new translation is created (cloned) when they want to edit a language, and they can then edit the entity just like any "normal" object.

![1_original_post](https://cloud.githubusercontent.com/assets/286492/8408350/b745ea62-1e6f-11e5-9517-ee7ed184ef2f.png)
![2_translating_to_english](https://cloud.githubusercontent.com/assets/286492/8408347/b73f8622-1e6f-11e5-8a79-cb8e3136d46c.png)
![3_translation_created_ready_to_edit](https://cloud.githubusercontent.com/assets/286492/8408349/b7438b3c-1e6f-11e5-9c45-544dea68efe4.png)
![4_translation_edition](https://cloud.githubusercontent.com/assets/286492/8408348/b73f93a6-1e6f-11e5-90dd-d44b37d0478e.png)


I'm not very satisfied with the URL handling yet : on one hand i'd like to be able to access translations through same GUID + lang param, but on the other hand this makes the system less generic, because of titles (we don't want to rewrite any page handler because on translation), and also SEO-friendly URLs. I'll certainly change that.

**Comment by ewinslow** [comment]
This isn't going to get a lot of attention from me over the next couple
weeks. I haven't gotten to glance through the code but I'd say keep at it,
ironing out details.

One thing I'd definitely caution against, however, is attaching view
specific information to the model (->view on entity makes me nervous).

**Comment by jdalsem** [comment]
Closing this due to lack of progress. Not going to add this feature to core. Leaving this in the domain of the plugins
