### ISSUE TITLE
To wrap or not to wrap (third party APIs)

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8100]
We have an open question about whether we should be doing things like what I've done in Elgg\Filesystem and Elgg\Cache: wrapping a third party API which is already an abstraction.

Arguments in favor:
 * our dependencies won't leak through to our users
 * allows us to fix/simplify the api without waiting for upstream patches
 * can make APIs consistent across the framework

Arguments against:
 * extra work (testing, documenting, etc.) compared to just using the API directly
 * hides new features of the underlying API until we explicitly expose them (this is a two edged sword).

So what should we do?
 * Wrap third party abstractions before using them
 * Case-by-case, but prefer to wrap 
 * Case-by-case, but prefer to avoid wrapping

I was going to add "don't wrap" but if we didn't wrap anything then there wouldn't be much reason for us to exist. I think we obviously have to wrap since we do want to provide a meaningful level of abstraction (e.g. entity storage) in some cases.

**Comment by beck24** [comment]
I see the biggest benefit of wrapping is the separation of the library from the end user.  It means we can upgrade/replace the library at will as long as the API remains consistent.  Not wrapping makes replacing/upgrading a library a potentially breaking change.
I think wrapping is the correct way to go, even though there is an annoying amount of work involved over using it directly.

**Comment by brettp** [comment]
My biggest complaint against wrapping is specific to the Filesystem classes right now because we're castrating a lot of features by hiding the library. The ROI of wrapping in this case is tiny, especially considering that it's not public API and is already being wrapped by 2 other APIs: ElggFile and ElggFilestore.

I think this is really as a case-by-case issue depending on the lib. I see a lot of projects that use guzzle and expose it so you can pass params directly to guzzle. That makes more sense for everyone than trying to re-implement guzzle's API with their own and having users re-learn a similar API.

**Comment by ewinslow** [comment]
@mrclay opinions?

**Comment by mrclay** [comment]
[runs out of room]

Definitely case by case leaning towards wrapping, but some APIs involve returning new objects and would very difficult/messy to wrap. Consider wrapping Symfony's Request, which has several property accessors of several types, each requiring its own wrapper.

**Comment by mrclay** [comment]
(I wish PHP had Scala's interface system where we could make a limited interface and declare our return values as implementing out limited interfaces without having to make wrappers at all.

**Comment by Srokap** [comment]
I'm generally for wrapping, even if it would mean just copying whole interface. Having well defined api is a very important stability feature, so we don't want for Elgg api to extend due to dependency upgrades. Additionally if we see some competing libs in particular area, I'd prefer to define api in the way that allows switching to the other one without much struggle or even more preferably to be replaced by the end users in their project.

**Comment by ewinslow** [comment]
It sounds we're collectively leaning toward case by case with a preference for wrapping.

I still agree with Brett that the filesystem wrappers are of questionable benefit currently, but they're also under our control and trivial to update.

I hate gray areas!

**Comment by ewinslow** [comment]
@mrclay I believe Go does something like that too, where you don't have to declare `implements` in order to pass as an implementation of the interface.
