### ISSUE TITLE
pass array to elgg_require_js

### ISSUE THREAD

**Issue by twentyfiveautumn** [Elgg/Elgg#8127]
https://github.com/Elgg/Elgg/blob/master/engine/lib/elgglib.php#L201
Is there any reason we could not pass an array here?
like ``elgg_require_js( array());``

**Comment by juho-jaakkola** [comment]
What is your use case?

**Comment by jdalsem** [comment]
Multiple required libs... i get it. Should not be that hard to do a foreach if it is an array

**Comment by jdalsem** [comment]
same also applies to `elgg_load_js` and `elgg_load_css`

**Comment by juho-jaakkola** [comment]
"Multiple required libs" is not a use case.

What feature requires you to include multiple separate libraries from one location and why?

**Comment by jdalsem** [comment]
> "Multiple required libs" is not a use case.

Why not? If i need functionality that for a certain function needs both the `jquery.accordeon` and the `lightbox` lib, i now need to do `elgg_require_js('lightbox'); elgg_require_js('jquery.accordeon')`.

It could be *nice* to be able to do: `elgg_require_js(['jquery.accordeon', 'lightbox']);`

I have recently needed to do:
```php
elgg_load_js('lightbox');
elgg_load_css('lightbox');
		
elgg_load_js('elgg.userpicker');
elgg_load_js('jquery.ui.autocomplete.html');
```
because of the autocomplete and the userpicker being used in the ajaxed lightbox content, i needed to load the libs manually (as both the userpicker and autocomplete stuff are not 'yet' able to be used in ajaxed content). BTW that was in Elgg 1.8, but similar situations could always arise. 

Passing an array could make it a few lines simpler, nothing more, nothing less. Just lazy

**Comment by twentyfiveautumn** [comment]
I'm sorry, I don't recall the exact use case I was looking at but similar to @jdalsem I needed to load two js scripts with different dependencies. And I can't see a downside to adding it

**Comment by hypeJunction** [comment]
I don't see harm in this, but I also wouldn't want to waste time on it.

**Comment by ewinslow** [comment]
Yea, I don't think this solves enough of a problem to warrant changing our API, documenting the feature, etc. etc. Just list them on separate lines.

**Comment by twentyfiveautumn** [comment]
Yeah, it's probably more work than it's worth for the amount of instances where it would get used.

**Comment by ewinslow** [comment]
@twentyfiveautumn thanks for understanding :)
