### ISSUE TITLE
Invalid language code added in 1.11?

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8230]
https://github.com/Elgg/Elgg/blob/1.11/mod/blog/languages/sr%40latin.php /cc @juho-jaakkola

**Comment by Srokap** [comment]
It comes from Transifex obviously https://www.transifex.com/projects/p/elgg-core/language/sr@latin/. Not sure why don't we have here just Serbian (there are total 6 types of Serbian apparently). Transifex doesn't follow strictly ISO standard and mixes two of them so I think we might expect more of those showing up.

We could either define mapping for nasty language codes to ie. `sr_latin` or live with them. I wonder if this code does actually work by any chance. Long time since I digged through i18n system. Having in docs currently handled formats might be helpful. I thought we wanted to handle `ISO 639-1` and chosen elements of `ISO 639-2`/`ISO 639-3`? Could actually allow the Unix-like locale codes. That would be `[language[_territory][.codeset][@modifier]]` that's supposed to be defined in [RFC 5646](http://tools.ietf.org/html/rfc5646) (which goes with formats much further than I'd like to support).

**Comment by juho-jaakkola** [comment]
I had missed that one.

**Comment by jdalsem** [comment]
Test suggestion for language codes https://github.com/Elgg/Elgg/issues/7154. We can do that as we have a complete list of all the (allowed) language codes in core

**Comment by juho-jaakkola** [comment]
Where is the list?

**Comment by jdalsem** [comment]
https://github.com/Elgg/Elgg/blob/master/engine/classes/Elgg/I18n/Translator.php#L422

**Comment by jdalsem** [comment]
The strange language is no longer present. #8954 should make sure it does not happen again
