### ISSUE TITLE
Discussion replies UX inferior to comments

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8235]
* In river view, the title of the target links to the comment, whereas discussion replies show a separate "view reply" link. I may actually prefer the discussion model, as I expect a title to link me to the post, not a reply.
* ~~Linking to discussion replies doesn't visually highlight the reply.~~
* ~~Discussion replies don't have the nice comment thread design.~~

Is our long term plan to make discussion replies into regular comments?

**Comment by juho-jaakkola** [comment]
I believe the only imperative reason we have a separate subtype for discussion_replies is for the ability to know when we should send notifications to members of the containing group instead of just the owner of the post.

> Linking to discussion replies doesn't visually highlight the reply.

This worked when I added the feature. Something may have broken/overridden it.

> Discussion replies don't have the nice comment thread design.

Yes, but neither do comments (yet)?

> Is our long term plan to make discussion replies into regular comments?

They could at least be closer to each other. But IMO replies are not semantically identical to comments, so it might be best to leave to possibility for plugin devs to handle them differently.

**Comment by mrclay** [comment]
I missed features based on Community.
