### ISSUE TITLE
Email notification method (_elgg_send_email_notification) does not take care about $result param

### ISSUE THREAD

**Issue by saeedsq** [Elgg/Elgg#8300]
Here is the scenario:

1) Register a hook on send, notification:email
elgg_register_plugin_hook_handler('send', 'notification:email', 'utility_send_email_notification_hook', 1);

2) send email & return true at the end of hook function utility_send_email_notification_hook

Result: System sends two emails
Expected outcome: System should send the email just once

**Comment by saeedsq** [comment]
Code Comments says:
 @param bool   $result Has anyone sent a message yet?

**Comment by SirbitoX** [comment]
I have this problem, either.
I think the reason is:
[_elgg_send_email_notification($hook, $type, $result, $params)](http://reference.elgg.org/notification_8php_source.html#l00195) doesn't check ```$result``` parameter to see whether it is ```false``` (the **hook** has been already handled by another plugin) or not. It should be check in very first lines of the function.

**Comment by SirbitoX** [comment]
@saeedsq I think your function should return **false** if it has handled sending the email. 
you said:
> 2) send email & return **true** at the end of hook function utility_send_email_notification_hook

**Comment by mrclay** [comment]
I believe @SirbitoX is correct. `_elgg_send_email_notification` should first check whether `$result` is already true, and bypass if so.

**Comment by mrclay** [comment]
Would anyone like to contribute a fix to the 1.11 branch? :) http://learn.elgg.org/en/1.11/contribute/code.html#pull-requests
