### ISSUE TITLE
Consider re-exposing ways to sniff action name

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8378]
See https://github.com/Elgg/Elgg/commit/35382fce5bcf0267c28c84cadab34350c22121dd#commitcomment-11400998

- We stopped putting action name in input in 1.9
- We stopped leaking core action() scope to action scripts in 1.11

**Comment by mrclay** [comment]
Against: Nowhere do docs say specific variables are passed to the action script.

For: Docs are often vague so it's reasonable for devs to inspect the include scope. 

Cc @hypeJunction

**Comment by mrclay** [comment]
The official way to do this is probably to register for the `action` hook and capture the name in some shared state.

**Comment by hypeJunction** [comment]
My current workaround is to grab __elgg_uri and get the action name from there. In theory, with the way Elgg actions are registered, action file would always know what action it is executing. In practice, if you want to do anything differently, that causes an issue. I am not sure if I am the only one who experienced inconveniences due to this change. If so, I don't mind letting it go. Whatever others think.

**Comment by mrclay** [comment]
I mostly think it's a problem that we stopped setting the "action" input, but not sure we should bring it back now.

Maybe we just document how to detect action name from the action hook?

**Comment by mrclay** [comment]
e.g.
```php
function capture_action_name($hook, $type) {
    set_input('action', $type);
}
elgg_register_plugin_hook_handler('action', 'all', 'capture_action_name');
```

**Comment by hypeJunction** [comment]
I think your approach is better as it will work with nested actions.

**Comment by mrclay** [comment]
How do you perform nested actions?

**Comment by hypeJunction** [comment]
By calling action($other) from action file.

**Comment by mrclay** [comment]
Not worth documenting this IMO.
