### ISSUE TITLE
Officially support nested actions

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8384]
At some point (1.9?) `action()` was made private but it's not clear why. Anyway, to avoid more accidental breaks (#8378) we should specify how this works. E.g. output buffers, the return value, do we provide awareness of being called from other action(s).

**Comment by mrclay** [comment]
E.g. If inner action forward()s, what happens to outer output buffer?

**Comment by hypeJunction** [comment]
Action forwarding was a roadblock in certain situations for me, so I have just included the other action file instead of using action().
I am not entirely sure we should be supporting nested actions out of the box, especially if the action service is going to be rewritten to allow classes. I think the need to use a nested action comes from bad API structure, where the alternative is to copy paste. So, for instance, a file upload action could be a nested action, with parent action setting container_guid, once the parent entity is created. But the same should be achievable with an a better API.
I would really like to explore the possibility of dropping the /actions namespace. Tt the end of the day it is only done for CSRF protection. We should be moving towards POST calls to standard Elgg routes.

**Comment by mrclay** [comment]
Sounds good. No nested actions! But actions are free to collaborate via existing mechanisms like hooks.
