### ISSUE TITLE
Resource views broke alternate viewtype renderings (RSS)

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8436]
Somehow resource views need to default to the "default" viewtype instead of the global viewtype. @ewinslow

**Comment by mrclay** [comment]
A simple fix in renderView:
```php
if ($viewtype === '' && 0 === strpos($view, 'resources/')) {
    $viewtype = 'default';
}
```

**Comment by mrclay** [comment]
I think we might want a new function:
```php
function elgg_view_resource($name, $expect_output = true) {
  $view = "resources/$name";
  if (!elgg_view_exists($name, 'default')) {
    return " something... ";
  }
  $output = elgg_view($view, [], false, false, 'default');
  if ($expect_output && $output === '') {
    return " something... ";
  }
  return $output;
}
```

**Comment by mrclay** [comment]
PR #8496

**Comment by hypeJunction** [comment]
Me no like. Why not use current viewtype? I want to be able to just drop in a json view and have an output without having to add more lines of code to the page handler.

**Comment by mrclay** [comment]
So you have a case for checking the current viewtype first. If we don't fallback to "default", none of the RSS feeds will work.

**Comment by mrclay** [comment]
@ewinslow you have any thoughts on supporting non-default viewtype resource views? I like that this would make it easy to make a completely custom version of a resource for JSON/RSS.

**Comment by hypeJunction** [comment]
Perhaps ```elgg_view_resource()``` could wrap the output with ```resource/default``` view, and we could use that as a shell for viewtypes currently in core?

**Comment by ewinslow** [comment]
Ah, OK, so after thinking on it for a while I think I finally understand why this is happening:

"RSS" viewtype doesn't fall back to "default", so when we attempt to elgg_view('resources/view') during an RSS request, nothing happens, and that's the expected behavior based on viewtype fallbacks. Maybe we should check if we're in a debug mode and throw an exception or something when elgg_view is called and the view doesn't exist at all, by extension or by fallback.

I think perhaps we could say that all resource views fall back to "default". So `elgg_does_viewtype_fallback("resources/*")` always returns `true` for any `*`.

But then when you render the resource view, you want to make sure that it still tries to render RSS for any sub-views.

Definitely want to keep the element of control for developers though. At any point they should be able to say, look, I don't want Elgg's help or indirection or whatever, I just want to write my own RSS feed or HTML or JSON from scratch. We should make sure that stays easy.

**Comment by mrclay** [comment]
I'm proposing: if view exists in the requested viewtype, use it. If not, check for the view in the "default" viewtype resource view. If both fail, show 404.

Whatever the logic, I'd rather it be in a function than baked into the already complete views system.

**Comment by ewinslow** [comment]
That logic sounds good to me.

**Comment by ewinslow** [comment]
elgg_view_resource it is!

**Comment by hypeJunction** [comment]
IMHO, registering viewtype fallback does the same thing. The problem is you
do not want to render random html stings in json/RSS output that come from
default viewtype.

**Comment by mrclay** [comment]
Give #8496 a look

**Comment by hypeJunction** [comment]
I am happy :) Thank you for listening to my vocal objections.
