### ISSUE TITLE
Restore _graphics files for BC

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8542]
See https://github.com/Elgg/Elgg/pull/8434#issuecomment-113786380. The win of getting rid of `_graphics/` doesn't seem worth the cost of breaking plugins who expect those files. `engine/views.php` makes it easy to keep that BC.

**Comment by ewinslow** [comment]
Copied from other convo:

> Any plugin using $image = elgg_get_site_url() . '_graphics/ will fail to work on Elgg 2.0 if it isn't updated.

I added a redirect for this in .htaccess so that plugins referencing them via url should still work.

However, if there are any direct filesystem references, those will fail. That doesn't seem like as much of a concern though.

**Comment by iionly** [comment]
@ewinslow are you referring to the line
```
RewriteRule ^_graphics/(.*)$ cache/0/default/$2
```
in .htaccess? If so, it doesn't seem to work for me for example with
```
$spacer_url = elgg_get_site_url() . '_graphics/spacer.gif';
```
It results in a 403 error.

**Comment by ewinslow** [comment]
That's the one. Getting that right would be my preferred way of fixing this
problem because in general we probably want to push people away from
relying on the exact filesystem layout. If we move elgg to a composer
dependency, for example, it will be located at vendor/elgg/elgg/.... Moving
_graphics back out of views system will not fix the issue in this case.

**Comment by iionly** [comment]
It seems to work with 
```
RewriteRule ^_graphics/(.*)$ cache/0/default/$1 [L]
```

**Comment by mrclay** [comment]
#8544
