### ISSUE TITLE
"Undefined index: id" in mod/embed/start.php (line 88, 89)

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8563]
...also in mod/ckeditor/start.php (40)

Inspecting menus

**Comment by iionly** [comment]
It seems I don't get any of the undefined issues you reported today. My test installation hasn't been updated with the changes made within the last 2 days though.

Could it be that all the issues you have noticed are caused by a PR merged within the last 2 days? https://github.com/Elgg/Elgg/pull/8547 would be my first guess.

**Comment by jdalsem** [comment]
Not an issue at this moment

**Comment by jdalsem** [comment]
Oops not looking at the right log... will fix this
