### ISSUE TITLE
Subject of discussion reply notifications are broken

### ISSUE THREAD

**Issue by teamwebgalli** [Elgg/Elgg#8590]
The subject for discussions reply are broken. With in the discussion_prepare_reply_notification() hook even if we set a hardcoded subject for notification entity, its returning the subject like 

> Re : Topic title.

When the subject is supposed to be like 

> New reply in topic: Topic title

Elgg 1.11.2

**Comment by juho-jaakkola** [comment]
Core forces comment and reply notifications to use ```RE:``` in the beginning because this helps some email clients to understand that it is a reply and show related emails as an email thread instead of multiple individual emails.

Does your use case get fixed if you unregister the hook handler ```_elgg_comments_notification_email_subject``` from the ```'email', 'system'``` hook?

**Comment by teamwebgalli** [comment]
@juho-jaakkola : My use case get fixed by modifying the comments hook. 

But I feel, this is not the right usage especially when we have a separate hook available for preparing the replies. The only advantage of using the comments hook is just to prefix with "RE". Why cant we use the same prefix with in the discussion reply hook?

**Comment by ewinslow** [comment]
Judging by the title of this ticket, this is WAI. Please open another ticket if there is a follow up issue.
