### ISSUE TITLE
Division by zero in ElggCrypto

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8603]
This keeps showing up in my WAMP logs:

[Sat Jun 27 14:39:36.712131 2015] [:error] [pid 2368:tid 968] [client 127.0.0.1:
59042] PHP WARNING: 2015-06-27 05:39:36 (PDT): "Division by zero" in file D:\\xxx\\engine\\classes\\ElggCrypto.php (line 131), referer: http://
xxx

**Comment by mrclay** [comment]
Opened https://github.com/GeorgeArgyros/Secure-random-bytes-in-PHP/issues/8

**Comment by mrclay** [comment]
Any ideas on how we can fix this locally?

**Comment by mrclay** [comment]
I bypassed the code paths with all the better random generators (openssl_random_pseudo_bytes, mcrypt_create_iv, /dev/urandom) so that the slow [microtime collection](https://github.com/Elgg/Elgg/blob/1.8/engine/classes/ElggCrypto.php#L122) would be done. Then I deliberately set $c2 = $c1 and $rounds to 0 to emulate this bug.

With those modifications I couldn't get a duplicate string within 40K calls to `getRandomBytes(24)`, which is used to generate the remember me tokens.

**Comment by mrclay** [comment]
In fact, even if I generate only 10 byte tokens, I don't get duplicates within 1M calls (ran out of memory).

Hence I'm fairly confident this bug lowers entropy in the rare case it occurs, but not enough be a security issue, and not enough to be the root cause of #8736.

**Comment by mrclay** [comment]
My research script: https://github.com/Elgg/Elgg/compare/1.11...mrclay:8603_testing

**Comment by mrclay** [comment]
@hypeJunction have you seen this error ever on a production server? Or any place other than your local machine?

**Comment by hypeJunction** [comment]
Quite possible I saw it before switching one of the servers to PHP 5.5, but
can't be 100% sure now. The logs were flooded with stuff at the moment.

**Comment by jdalsem** [comment]
@hypeJunction did you ran into this recently? I have never seen this warning on any of our setups and it is not reproducable. If you have more intel, please reopen.

**Comment by hypeJunction** [comment]
Hasn't happened since Steve updated crypto

**Comment by iionly** [comment]
For reference: https://bugs.php.net/bug.php?id=64633

There's a report that the division by zero error occurs on an IIS 7.5 Windows server 2008 installation with php 5.5 at https://elgg.org/discussion/view/2606749/elgg-23-division-by-zereo.
