### ISSUE TITLE
Add docs/guides/upgrading docs for #8578

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8625]
#8578 removed a bunch of CSS classes. Maybe we don't need to list them all, but theme plugin authors will surely need some heads up.

**Comment by jdalsem** [comment]
Isn't that why it is mentioned in the breaking change commit message? Or should we mention a global "be adviced... a lot of css has been changed, but mainly icons"

**Comment by ewinslow** [comment]
@jdalsem We have been duplicating breaking changes between the commit message and the RST upgrade guide. It's a bit annoying, but it does allow us to glom several related breaking changes together like removed views, removed actions, etc.

Also, sometimes the fix for past breaking changes are superceded by future breaking changes. These need to be retroactively updated, which isn't possible to do with commit messages.

**Comment by mrclay** [comment]
Slightly diff audiences, too: the upgrading guide should be geared toward helping devs update plugins, the commit message notices don't need as much detail IMO. We need some documented guidelines here.

**Comment by mrclay** [comment]
PR #8662
