### ISSUE TITLE
Streamline comment email notifications

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8781]
I vote we cut out 90% of the non-content text and/or move it into email metadata.

Before:

```
Subject: Re: Elgg.org merged with Community, upgraded to Elgg 2.0.0-dev
From: no-reply@elgg.org

You have a new comment on your item "Elgg.org merged with Community,
upgraded to Elgg 2.0.0-dev" from Michele. It reads:

> ridiculously faster load times over flaky connections

Today I'm on a 2.8Mb network.....couldn't believe how fast pages load

This is a dream for all of us mantaining a community....hope plugin devs
will get at least 10% excited as I am to start upgrading :D

As always, thank you all guys!


To reply or view the original item, click here:

https://elgg.org/comment/view/2260471/2260427

To view Michele's profile, click here:

https://elgg.org/profile/michele

Please do not reply to this email.
```

After:

```
Subject: Re: Elgg.org merged with Community, upgraded to Elgg 2.0.0-dev
From: "Michele (via Elgg.org)" <no-reply@elgg.org>

> ridiculously faster load times over flaky connections

Today I'm on a 2.8Mb network.....couldn't believe how fast pages load

This is a dream for all of us mantaining a community....hope plugin devs
will get at least 10% excited as I am to start upgrading :D

As always, thank you all guys!

Reply: https://elgg.org/comment/view/2260471/2260427
```

**Comment by juho-jaakkola** [comment]
I really like the suggestion. My only concern is that even with the old way people often think they can reply to the notification directly via email. The new way would make it even more unclear that it is a notification and not an email sent directly by the commenter.

I wonder how we could avoid this. Using HTML emails and styling them not to look like a regular email might be quite effective.

**Comment by juho-jaakkola** [comment]
Sites can of course change the email content how they like, so I'm not blocking.

**Comment by ewinslow** [comment]
I think the ideal solution is to let people reply to the emails. Wonder how
complicated that is?

**Comment by beck24** [comment]
We've done it with a number of sites - it requires some setup on the email side of things so it won't work out of the box.  You need a catch-all email address so you can send notifications to something like reply-[crypto-token]@example.com

PHP has native imap reading capabilities, on cron it checks the email folder, parses the email to match the crypto token to an ElggObject that identifies the discussion.  The content of the email is parsed and posted as a reply/comment (since this is done while logged out it needs some explicit permissions auditing).

One big problem we've run into is automatic out of office replies - annoying when they clutter up the site with such responses, and worst case they can sometimes get caught in infinite loops of replies triggering notifications triggering replies.  We've got some filtering in place to try to combat that, though it's only marginally effective as people write their own out of office replies with different language structures - so far we've only dealt with english but the problem would be compounded dealing with multiple languages.  A system of strict duplicate checking for replies over a small number of characters seems to have worked decently well to stop the loops.

**Comment by ewinslow** [comment]
Moved reply-by-email discussion to https://github.com/Elgg/Elgg/issues/8795.
