### ISSUE TITLE
Ignore access for 'register','user' hook

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8874]
Currently, each handler listening to `'register','user'` has to wrap their code in ignore access API to get things done. IMHO, it would make sense to wrap the hook trigger with ignore access API and discourage the use of `elgg_*_ignore_access()` by plugins.

**Comment by jdalsem** [comment]
I like the current approach where plugin developers need to carefully think about how things work so i see no need to discourage the use of `ignore_access`. If you think the `'register', 'user'` hook needs to be wrapped in `ignore_access` feel free to do so in a PR. Closing this for now due to lack of activity
