### ISSUE TITLE
Symlinks not working?

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8878]
@ewinslow  Something odd is happening with my project installed with a starter-project. I activate a plugin, it activates ok, but then gets disabled saying can not include start.php. Have tried both alpha and master, same thing. Looks like symlinking is not really working as expected. I am on Windows.

**Comment by jdalsem** [comment]
Did you figure this out?

**Comment by hypeJunction** [comment]
Starter project was not something I enjoyed working with, so I haven't had issues. But I think others were reporing in the community.

**Comment by beck24** [comment]
I experienced something similar then realized it's because I used composer on a host system but the build was in a shared directory for a virtual machine, so the symlinks were created referencing paths in the host machine that didn't exist in the VM.  Could that have been your case @hypeJunction ?  I doubt this would explain all reports from the community.  Not sure how many people are regularly using VMs

**Comment by hypeJunction** [comment]
It was a while ago. I think it worked for me at some point so this initial report was actually resolved.

**Comment by hypeJunction** [comment]
Closing as dupe #9077. I am sure it will get tested and solved then.
