### ISSUE TITLE
Pages Write Access: Missing Access Level Name

### ISSUE THREAD

**Issue by susiefen** [Elgg/Elgg#8905]
Newbie here, and just started working on Elgg and Git a few days ago. Although this looks like a simple fix, I don't want to change anything because I am still learning how this all works and don't want to break anything. 

When creating a page, the write access has four levels; private, friends, logged in users and "missing access level name". I think this is supposed to be public. 

<img width="1182" alt="screen shot 2015-09-03 at 9 00 27 am" src="https://cloud.githubusercontent.com/assets/13153172/9658867/a2e3f490-521a-11e5-9686-0663c45a161d.png">

**Comment by juho-jaakkola** [comment]
Which Elgg version are you using?

Please disable all non-bundled plugins and verify whether the problem occurs when using just the default plugins.

**Comment by hypeJunction** [comment]
I have seen this happen with walled garden enabled. Has been reported
somewhere

**Comment by beck24** [comment]
Found the reason for this - site default access is set to public, but the pages plugin removes that as an option from the write access array
The input/access view then treats it as a custom acl an attempts to find the name, but since ACCESS_PUBLIC is not a real acl it can't find it and sticks in the placeholder text.

Pages plugin should modify the view vars and modify the value if ACCESS_PUBLIC is being passed due to site default access.

**Comment by beck24** [comment]
Actually, if a core access level is not in the array should the input/access view display it anyway?  This could be fixed at the core input/access view.  Otherwise unwanted access levels will present any time it's passed as a default value.

**Comment by beck24** [comment]
I decided the input/access view should stay as-is and this should be the responsibility of the pages plugin to enforce its allowed values.
