### ISSUE TITLE
River replying feature is broken for discussions

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8932]
Clicking the speech-bubble icon should open a replying form, but it's now happening.

**Comment by iionly** [comment]
The latest replies in a discussion are also not displayed below the discussion starter entry in the river. While this might not be directly related to the failure of the reply form but the latest replies being displayed might be a nice to have feature. I guess the reply feature fails to work because the replies on discussions are not comment. While fixing this it might also be possible to display discussion replies instead of looking for comments if the river object is a discussion entity.

**Comment by mrclay** [comment]
The view river/object/discussion/create renders non-existent view river/elements/discussion_replies.

**Comment by mrclay** [comment]
@juho-jaakkola I see 1.12 still has the river/elements/discussion_replies view. Was it intentional to get rid of it in 2.0?

We could solve this particular issue by using `#comments-add-GUID` in discussion_add_to_river_menu() instead of `#discussion-reply-GUID`, but I don't know what we'd lose doing that.

**Comment by mrclay** [comment]
I figured it out. PR #8933

**Comment by mrclay** [comment]
@iionly the PR fixes the issue you're seeing as well
