### ISSUE TITLE
Require less than 100% completeness when pulling translations

### ISSUE THREAD

**Issue by juho-jaakkola** [Elgg/Elgg#8959]
I noticed that Italian translations for engine resource are currently at 98% which causes it to be excluded when pulling translations using Transifex client.

It's a bit too drastic to remove the whole resource when only a couple of translation are missing. I suggest we reduce the amount to 95%.

**Comment by iionly** [comment]
Maybe it would make sense to not only consider the completenes per language file but also the total completeness of translations. The problem I see with 100% completeness required per file is that you might lose a possible large part of a translation (e.g. the engine file) of an otherwise almost complete translation just because it might not get updated soon enough after English strings have changed and the following (automatic) release. On the other hand there a quite a number of language included in the releases that are basically unuseable (based on total completeness) just because there a 100% of some small language files translated.

**Comment by juho-jaakkola** [comment]
Transifex client allows you to define minimum translation completeness only per resource, not for the project as whole.

**Comment by juho-jaakkola** [comment]
Well, we could of course make the Elgg release script to do that after the translations have been pulled in. But I'm not sure if it's worth the trouble.

**Comment by iionly** [comment]
I guess it might be the only way to adjust the Elgg release script then.

> But I'm not sure if it's worth the trouble.

I think it does matter. There are several translations with very low total completeness that are of no use at all at the moment. And there hasn't been any progress on these translation for quite some time. My guess is that the guys who started the translation for these languages realized that it takes much more time to complete the translations than they thought originally and they might have given up. Does it make any sense to keep them in their present incompleteness within every new release?

I would say a minimum of total completeness of at least 50% - maybe even > 70% - would make sense for these translations to have any use. Maybe such a minimum total completeness would even be some kind of motivation for people to continue working on their translations to get them included.

Should I open a separate issue about the minimum total completeness of translations?

**Comment by juho-jaakkola** [comment]
Yeah, a separate issue would be good.

**Comment by juho-jaakkola** [comment]
Adding to the 2.0.x milestone to make sure non English-speaking people get a good first impression of Elgg v2.

**Comment by iionly** [comment]
I've changed my mind. I won't open an issue about total translation completeness. On my development installations I don't care and on production installations (where I don't plan to use composer based installs) I will just clean up the language files on my own by a script instead.
