### ISSUE TITLE
can_edit_access_collection() and ignored access

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9026]
`can_edit_access_collection()` does not respect access overrides, and admins thus can not edit them.

**Comment by mrclay** [comment]
This was logic mixed with a big change https://github.com/Elgg/Elgg/commit/9a53ddf57cdbf557b0d4f21d0fdf01b4b92569c4#diff-23234856e075522f9fb90e4cbc1d4ae1R442 but the comment makes it seem intentional `don't ignore access when checking users`

**Comment by beck24** [comment]
Yes this is intentional

The problem before is that if you called it on a collection that a user couldn't edit, eg.

    can_edit_access_collection(123, $userA->guid);

while logged in as admin (not $userA), it would always return true, indicating that $userA could edit that access collection, which is wrong.  Now it properly returns false.
I don't see what would prevent an admin from editing a collection though.

**Comment by hypeJunction** [comment]
Nothing prevents an admin from editing a collection, but I needed to add an additional check to see if an admin is logged in.
