### ISSUE TITLE
ElggFile entity storing entire site config

### ISSUE THREAD

**Issue by xpoarte** [Elgg/Elgg#9081]
Hello,
I am working on new versions and I have noticed that the images uploaded from file, tidypics and other plugins, slow down the performance, I found that the 'entities' of the images in versions 11 and 12 contain a lot of data, including all $vars or $params site,

I send a comparison of the same file from the file upload plugin in elgg 1.9.7 and 1.11.4
https://www.dropbox.com/s/069ti00xw9backs/elgg9.txt?dl=0
https://www.dropbox.com/s/sg1otwbsmvsyr3j/elgg11.txt?dl=0

sorry if my explanation is confusing, I do not speak English

I just found this difference and still have no idea where it is producing, the class in both versions are the same, if I find something I will tell you

**Comment by beck24** [comment]
Confirmed on 1.12

**Comment by mrclay** [comment]
I just ran into this 2 hours ago! The ElggFilestore object needlessly holds a copy of $CONFIG. This gets stored in memcache :(

**Comment by mrclay** [comment]
I don't see how this would slow anything down, though.

**Comment by iionly** [comment]
Copy of $CONFIG due to https://github.com/Elgg/Elgg/commit/ef5bca6259bddf5a0e1633712f05ba809c22c561 ?

**Comment by mrclay** [comment]
Yes.

**Comment by mrclay** [comment]
If we can wait until 2.x I have a big patch coming.

**Comment by xpoarte** [comment]
I do not understand why is necessary to add the $CONFIG to the _construct of the file entity, but in the class ElggDiskFilestore appears $this->CONFIG = $CONFIG;
Disabling it I can not distinguish the difference in performance, but when I check I find a small delay in tenths of a second, when I load 16 images, I do not think it's important the time difference.
About my doubts, the topic can be close, thanks :D

**Comment by mrclay** [comment]
This is the change needed: https://github.com/Elgg/Elgg/pull/9080/files#diff-66e6e1c8f6c0ef9b403c0cf4160d1cf5

**Comment by iionly** [comment]
I would really think it better to fix this specific issue already on Elgg 2.0 AND 1.12 and not wait for 2.1.

The questions that come to my mind:
* is it safe to just remove the $this->CONFIG = $CONFIG line from the ElggDiskFilestore constructor?
* do any other entity class constructors do the same or is it only happening in the ElggDiskFilestore class?
* how to deal with existing entities that contain the whole site config?
* how to deal with entities of 3rd party plugins that use classed extended from the ElggFile class? All these extended classed will have the same problem with their entities containing the site config.

**Comment by mrclay** [comment]
It should be fixed as far back as 1.10 because $CONFIG (containing DB credentials) is being serialized in memcache, which is a security no no. The better fix is to just not serialize `$this->filestore` by implementing a `__sleep` method.

In no other way is this a bug; it just wastes space in memcache and slows (un)serialization. $CONFIG is an object (copied by reference) so these take up no memory. The other services that store $CONFIG are fine as they aren't stored in entities or other serialized objects.

**Comment by iionly** [comment]
I was (wrongly) assuming that the content of $CONFIG is saved as metadata for each ElggFile entity. That's why I was worried about the impact on 3rd party plugins. But as it seems "only" a memory issue (briefly tested by commenting out the problematic line in the constructor) I think there shouldn't be any fixes necessary to be done within 3rd party plugins itself. Good thing!

Memcache issue (security related) would indeed mean fixes back to 1.10 due to the support promised on the release policy page... Troublesome thing!

**Comment by mrclay** [comment]
PR #9109
