### ISSUE TITLE
Group with LOGGED_IN access and hidden group support disabled

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9183]
I am looking at the group edit action, and it seems that group's access_id is always default to public, if hidden groups are disabled.

**Comment by hypeJunction** [comment]
And the form also never shows access picker with logged_in/public if hidden groups are disabled.

**Comment by juho-jaakkola** [comment]
Are you sure there isn't a hook handler that alters the access_id?

**Comment by hypeJunction** [comment]
The action sets it to public, there are no hooks for access_id (only some
logic if input is set to private).

We really need to move everything outside of the action file. If I were to
iterate through groups and set owner_guid to something else, all icons
would be broken. All that madness needs to be happening in event handlers
or class methods. Same with renaming the group outside of the action, or
changing any attribute for that matter.

**Comment by hypeJunction** [comment]
While on this, we need to make sure we do not duplicate `Group-members only` and `Group: group name` in the visibility input: see here https://github.com/hypeJunction/Elgg-prototyper_group/blob/master/views/default/input/groups/visibility.php

**Comment by mrclay** [comment]
I think the idea was that access_id would always be public if "hidden groups" is disabled. I don't think we've had a regular access_id selector on the group edit form for some time.

**Comment by hypeJunction** [comment]
Still that doesn't explain why groups are public even if walled garden is
on.

**Comment by mrclay** [comment]
If walled garden is on, ACCESS_PUBLIC is effectively the same as ACCESS_LOGGED_IN so why does it matter? Are you suggesting we support 3 values for group visibility (public, logged in, and members-only)?

**Comment by hypeJunction** [comment]
I just say we need some uniformity and clarity in group form and action.
Displaying and setting of visibility level is too convoluted and magical.

**Comment by jeabakker** [comment]
Users and groups by default have no access control.

For group there is an option to enable access control it's called "Hidden groups".
When access control is enabled on groups it respects the additional restrictions based on the site setting "walled garden".

The access control for groups respects when is shown on the form, if it's not shown on the form it apparently doesn't matter.

Walled garden controls url/route access NOT content access.

Since there is no clear problem reported and no suggestion on other improvements closing this ticket.
