### ISSUE TITLE
Update CKEditor & add "Code Snippet" addon

### ISSUE THREAD

**Issue by KitsuneSolar** [Elgg/Elgg#9283]
Hi!

I propose to update the "CKEditor" to the latest version.
And add "Code Snippet" addon: http://ckeditor.com/addon/codesnippet

I already did and not found problems.

**Comment by smellems** [comment]
I made a pull request to update the CKEditor to the latest version of the Full package.  I added the `autogrow `plugin since it was already there.

Adding the codesnippet plugin requires `lineutils`, `widget` and `widgetselector`.  I was'nt sure if you wanted to add these so I left them out.  I can add them if that's what is decided.

**Comment by jdalsem** [comment]
ckeditor is updated to latest 4.7.3 version in master branch. no other than default plugins are available. Additional plugins need to be provided by other elgg plugins.
