### ISSUE TITLE
GC racing conditions

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#9286]
We encountered a racing condition between GC metastrings and another plugin.

The problem:
In my plugin i have a cron (hourly) and it sets a metadata value which is a timestamp (so pretty unique).
At the same time GC (weekly, so different process) is cleaning up the metastrings table and this can cause the problem
- `$my_object->ts = time()`
- this checks metastring => it doesn't exists => insert new metastring
- GC metastrings detects newly added ts => isn't used => so remove
- `$my_object` insert in metadata the new metastring id (which doesn't exists anymore)

Next time i request `$my_object->ts` it's empty :(

Suggested solution:
- clean all the metastrings but the last 100 (or whatever number we can come up with)

**Comment by bruno-infotrad** [comment]
I thought metastrings were deleted only when it was not associated with either a metadata entry or an annotation.

**Comment by jeabakker** [comment]
@bruno-infotrad true, but my usecase is in the mili-/nano-seconds between the insert in metastring and metadata ;)

**Comment by bruno-infotrad** [comment]
I ran into a similar problem a while ago: I was creating a time stamp to track when a user had last accessed the page and I was calling the garbage collector in the page I was creating the time stamp in. Not sure if your problem is similar. In my case, I just removed the call to the GC cleanup as I figured a few hundred unused metastrings lingering in the DB for a few days were not that bad.

**Comment by mrclay** [comment]
Leaving the newest strings in place sounds good.

**Comment by jdalsem** [comment]
metastrings no longer exist in a separate table in Elgg 3.0. This specific situation will not be able anymore.
