### ISSUE TITLE
Notifications only check for hook handlers registered with specific types

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9325]
Notifications detects new style hook-based set up using hooks `->hasHandler('prepare', $type)`. This fails if your handler is registered using the "all" keyword, because hasHandler looks for a specific registration name/type pair.

- edited by @mrclay

**Comment by mrclay** [comment]
This is internal, so what's the concern. For 2.0 here's a PR to document it #9326.

**Comment by hypeJunction** [comment]
My problem is with the use of hasHandler in notifications service. I want to register a single handler for all 'prepare' hooks, but it's not possible.

**Comment by mrclay** [comment]
I hope it's OK I rewrote the description. The problem is we're using handler presence as an API switch (maybe unwisely). If I register a universal *menu* handler for [prepare, all], then we'll end up switching to the new API possibly in error.

Ideally the API would have just called a hook and used the return value to determine whether to use the new API.

**Comment by mrclay** [comment]
may be of interest to @juho-jaakkola

**Comment by hypeJunction** [comment]
The handlers would have to sniff the hook type to decide whether they have
to act upon it. I suppose Calling deprecated handlers would be wiser based
on return.
