### ISSUE TITLE
Return composer.lock to the repo

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#9430]
- Much faster composer installs (assets plugin is particularly slow)
- Faster Travis builds and zip releases
- Stop causing PR tests to fail due to changes in unrelated dependencies
- Stop causing PR tests to fail due to GitHub API limits (we're working around this now but still occasionally hit it)
- Devs get predictable installs
- Easier to support zip releases because we can actually duplicate code
- (anecdotal) Drupal commits its lock.

Else I think we should require specific versions of assets at least.

**Comment by mrclay** [comment]
Vast majority of frameworks don't commit lock, so this is probably a bad idea.

**Comment by hypeJunction** [comment]
I am changing my stance on this.

A successful build is tied to specific versions of vendor libraries. Arbitrary changes in vendors result in havoc, as mentioned by @mrclay. 

Changes to vendor libraries should be reflected in the changelog: if we want a vendor library updated, we make a `feature` pull request listing new version numbers. IMO vendor updates should only take place in minor releases (unless we update a specific vendor with a patch release).

Additional benefit: Scrutinizer currently fails because it doesn't know how to install composer plugins (bower assets can not be resolved to installable packages). Adding the lock file will give us proper inspection results.

See some experiments: #10020

**Comment by mrclay** [comment]
👍 👍 👍
