### ISSUE TITLE
Teach elgg/Ajax to work with absolute URLs

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9564]
When we render DOM elements we tend to normalize URLs and client side we use `$.attr()` to retrieve those URLs. `elgg/Ajax#path` is not really suitable unless we denormalize the URL into path and query data.

**Comment by mrclay** [comment]
Right, the path() call works but the wrong hook types will be used.

- `path('http://example.org/elgg/foo')` should be interpreted as `path('foo')`.
- What about `path('/elgg/foo')`?
- What about queries and fragments?

Here's my thinking: For all methods, queries are passed through to the underlying XHR URL, but neither query nor fragment go in hook types.

For the hook type in path() and action(), we strip the leading site URL, and then strip any remaining leading `/`. So `/elgg/foo` is interpreted as `elgg/foo`.

So for more reliable usage, devs should use `$.prop('href')` instead of attr, that way always getting a full URL.

**Comment by mrclay** [comment]
And of course in action() we don't need to decorate options.data if the query has CSRF tokens.

**Comment by mrclay** [comment]
Technically someone could be tying hooks to `path:/foo` and this would break by normalizing to `path:foo` but I think that's a risk we have to take.

**Comment by hypeJunction** [comment]
I agree that we should pass normalized URL to `fetch` and denormalize it for hook names. Or maybe it's just easier to forget about granular hooks and let callbacks sniff the URL/path, as we do in PHP.

**Comment by mrclay** [comment]
Hook handers can already register for `all`, and/or sniff the URL from `params.options.url`.

**Comment by mrclay** [comment]
I'm rolling this into #9547
