### ISSUE TITLE
elgg/Ajax and views that forward

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#9798]
In case a view forwards during an elgg/Ajax request with an error code:
1. Should we use output buffer as an error message?
2. Should we use system message registers?

**Comment by mrclay** [comment]
I do this in a recent PR. Check system error register. If empty, register the HTTP message as an error. Send back JSON wrapper (with error and deps). I had to move these out of hooks because neither the server nor client should fire ajax_response, but we do want messages transfer. My PR improving elgg/Ajax handles this situation.

**Comment by hypeJunction** [comment]
Could you post the issue number? Should we dig into it and merge or should I just cherry pick the changes? What's your feeling?

**Comment by mrclay** [comment]
Basic changes are in https://github.com/Elgg/Elgg/pull/9776/files#diff-d9caa93e5048bd31fddf93e78f131f12L59 be would need manually adapting to what you have.

**Comment by mrclay** [comment]
I have a branch ready for this, but we need #9777 to be accepted first, otherwise server messages will be lost and not shown to user.

**Comment by hypeJunction** [comment]
Bottomline: forget that `forward()` exists and don't ever use it. Throw an `HttpException` if you have to.
