### ISSUE TITLE
Fix community.elgg.org certificate errors or fix links to point directly to elgg.org

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#9818]
There are lots of links in the docs pointing to https://community.elgg.org. These can generally be fixed by switching them to elgg.org, but that seems like not the best solution since community.elgg.org links ideally would just keep working...

**Comment by iionly** [comment]
Needs love.

Most likely the problem with community.elgg.org urls could be fixed by including the "community" subdomain in the Let's encrypt config (as the "learn" subdomain seems to be). Then it would likely not be necessary to change any existing links on the community site (which wouldn't fix the issue with bookmarks and external links anyway).

**Comment by jdalsem** [comment]
I believe this is fix. @jeabakker you did something right?

**Comment by jeabakker** [comment]
Yes I did. community.elgg.org is now included in the Let's Encrypt config
