### ISSUE TITLE
elgg/dev/gear.html is not being added to simplecache

### ISSUE THREAD

**Issue by propertunist** [Elgg/Elgg#9902]
i am seeing an ajax and 404 error on all pages in my test site (2.1.2) and upon investigation it relates to the 'cogs' / 'gears' icon from developer tools when it is displayed on all pages. on my local server the file /elgg/dev/gear.html.php correctly finds it's way into the simple cache directory when a page is viewed. on my remote testing server that doesn't occur and i get a 404 error.
i have no idea why this is occurring presently as i have not seen any other cache errors.

**Comment by iionly** [comment]
Have you tested with exactly the same set of 3rd party plugins on both sites? Are you sure that it's not a plugin issue?

**Comment by propertunist** [comment]
yes, i am using the same plugins on both sites. i don't presently know anything about the cause of the issue - other than what i have said here. i am unlikely to dig deeply into this of my own accord for a while as i have so many other tasks that are a higher priority here. if anyone has any ideas of tests to do then i will happily do them though.

**Comment by iionly** [comment]
Are you using some kind of CDN on your remote server? The developers plugin uses the requirejs/amd text loader plugin:
```
var gear_html = require('text!elgg/dev/gear.html');
```
It seems this is the only place in Elgg core the text loader plugin is used. With CDNs it seems to be problematic. It seems that the text plugin tries to add a ".js" to the file name if it notices a file is hosted (cached?) on another domain. But with gear.html the filename is gear.html.php actually (and this file is cache with simple cache in Elgg).

Unfortunately, I have no experience with CDNs at all and also not much knowledge about requirejs. So, I have no idea if usage of a CDN is the explanation of the problem here. Let's see if a core dev can enlighten us.

**Comment by mrclay** [comment]
Do you get a 404 error? What URL is requested?

**Comment by propertunist** [comment]
@mrclay this is the error message in firefox's console (linux is similar but also references ajax:
```
Error: https://test.ureka.org/cache/1466022666/default/elgg/dev/gear.html HTTP status: 404
text.get/xhr.onreadystatechange()
 text.js:18
 text.js:18:128
```

**Comment by propertunist** [comment]
@iionly yes, i am using CDNs for some of the main JS files and static images from my site's theme. i haven't encountered any known issues with them so far.

**Comment by mrclay** [comment]
Reopen if you find more info on this error.

**Comment by iionly** [comment]
I think I did post some possible reason for the error already. Not having the option to test with CDN I can't verify this on my own. Would it help renaming the file gear.html.php to gear.html.js for testing to see if it makes a difference?
